//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol _TtP8sharingd25SDAirDropListenerDelegate_;

__attribute__((visibility("hidden")))
@interface _TtC8sharingd17SDAirDropListener : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: listener
}

- (void).cxx_destruct;	// IMP=0x00000001001f0d24
- (id)init;	// IMP=0x00000001001f0d5c
- (void)dealloc;	// IMP=0x00000001001f0d00
@property(nonatomic, readonly) NSString *description;
- (void)networkOperation:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001001f09d8
- (void)stop;	// IMP=0x00000001001f09a0
- (void)start;	// IMP=0x00000001001f0914
@property(nonatomic) __weak id <_TtP8sharingd25SDAirDropListenerDelegate_> delegate; // @synthesize delegate;

@end

