//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandler.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface _TtC8sharingd19SDAirDropHandlerIPA : SDAirDropHandler
{
}

- (id)initWithTransfer:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x0000000100208d90
- (void)updatePossibleActions;	// IMP=0x0000000100208c84
@property(nonatomic, readonly) NSString *singleItemActionTitle;
@property(nonatomic, readonly) NSString *suitableContentsDescription;
- (long long)transferTypes;	// IMP=0x0000000100207268
@property(nonatomic, readonly) _Bool canHandleTransfer;

@end

