//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC8sharingd26SDAirDropHashStoreInMemory : _TtCs12_SwiftObject
{
    // Error parsing type: , name: longToEntry
    // Error parsing type: , name: medToEntry
    // Error parsing type: , name: shorts
    // Error parsing type: , name: initialized
    // Error parsing type: , name: cnStore
    // Error parsing type: , name: storePreviouslyExisted
}

@end

