//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, SDStatusMonitor;
@protocol SDAirDropInformationDelegate;

__attribute__((visibility("hidden")))
@interface SDAirDropInformation : NSObject
{
    _Bool _started;	// 8 = 0x8
    SDStatusMonitor *_monitor;	// 16 = 0x10
    NSMutableDictionary *_properties;	// 24 = 0x18
    id <SDAirDropInformationDelegate> _delegate;	// 32 = 0x20
}

@property __weak id <SDAirDropInformationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010012c974
- (void)stop;	// IMP=0x000000010012c91c
- (void)start;	// IMP=0x000000010012c8cc
- (void)removeObservers;	// IMP=0x000000010012c87c
- (void)addObservers;	// IMP=0x000000010012c708
- (void)somethingChanged:(id)arg1;	// IMP=0x000000010012c6fc
- (void)setInformationAndNotify;	// IMP=0x000000010012c310
- (void)setProperty:(void *)arg1 forKey:(id)arg2;	// IMP=0x000000010012c200
- (_Bool)boolValue:(void *)arg1;	// IMP=0x000000010012c1b0
- (void)dealloc;	// IMP=0x000000010012c164
- (id)init;	// IMP=0x000000010012c0b0

@end

