//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandler.h"

@class SFSharablePassword;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerCredentialLinks : SDAirDropHandler
{
    SFSharablePassword *_credential;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010003bedc
- (void)updatePossibleActions;	// IMP=0x000000010003bca4
- (long long)transferTypes;	// IMP=0x000000010003bc6c
- (id)suitableContentsDescription;	// IMP=0x000000010003bac0
- (void)handleAction;	// IMP=0x000000010003ba04
- (_Bool)canHandleTransfer;	// IMP=0x000000010003b8cc

@end

