//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _TtC8sharingd27SDAirDropContactHashManager : NSObject
{
    // Error parsing type: , name: hashManagerQ
    // Error parsing type: , name: bucket
    // Error parsing type: , name: contactStore
    // Error parsing type: , name: hashDB
    // Error parsing type: , name: activated
    // Error parsing type: , name: updateTimer
    // Error parsing type: , name: meCardInfo
    // Error parsing type: , name: numUnpersisted
    // Error parsing type: , name: hashesAreCorrectKey
}

+ (id)shared;	// IMP=0x00000001001d6bb0
- (void).cxx_destruct;	// IMP=0x00000001001def70
- (id)init;	// IMP=0x00000001001d72a8
- (_Bool)acquireTokenForIdentifier:(unsigned long long)arg1;	// IMP=0x00000001001d6c00

@end

