//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary, NSError, SDNetworkOperation, _TtC8sharingd17SDAirDropListener;

@protocol _TtP8sharingd25SDAirDropListenerDelegate_
- (void)listener:(_TtC8sharingd17SDAirDropListener *)arg1 informationDidChange:(NSDictionary *)arg2;
- (void)listener:(_TtC8sharingd17SDAirDropListener *)arg1 didReceiveNewRequest:(SDNetworkOperation *)arg2;
- (void)listener:(_TtC8sharingd17SDAirDropListener *)arg1 didReceiveError:(NSError *)arg2;
@end

