//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface AWDSharingContinuityKeyboardTriggered : PBCodable <NSCopying>
{
    unsigned long long _timestamp;	// 8 = 0x8
    int _rssi;	// 16 = 0x10
    NSString *_sessionUUID;	// 24 = 0x18
    int _smoothedRSSI;	// 32 = 0x20
    struct {
        unsigned int timestamp:1;
        unsigned int rssi:1;
        unsigned int smoothedRSSI:1;
    } _has;	// 36 = 0x24
}

@property(nonatomic) int smoothedRSSI; // @synthesize smoothedRSSI=_smoothedRSSI;
@property(nonatomic) int rssi; // @synthesize rssi=_rssi;
@property(retain, nonatomic) NSString *sessionUUID; // @synthesize sessionUUID=_sessionUUID;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;	// IMP=0x00000001000de098
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000ddf7c
- (unsigned long long)hash;	// IMP=0x00000001000ddeb0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000ddd74
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000ddc74
- (void)copyTo:(id)arg1;	// IMP=0x00000001000ddbac
- (void)writeTo:(id)arg1;	// IMP=0x00000001000ddaf4
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000ddaec
- (id)dictionaryRepresentation;	// IMP=0x00000001000dd588
- (id)description;	// IMP=0x00000001000dd4d4
@property(nonatomic) _Bool hasSmoothedRSSI;
@property(nonatomic) _Bool hasRssi;
@property(readonly, nonatomic) _Bool hasSessionUUID;
@property(nonatomic) _Bool hasTimestamp;

@end

