//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface AWDSharingContinuityKeyboardResult : PBCodable <NSCopying>
{
    unsigned long long _timestamp;	// 8 = 0x8
    unsigned int _bannerVisibleMs;	// 16 = 0x10
    unsigned int _beginEditingCount;	// 20 = 0x14
    unsigned int _closeAction;	// 24 = 0x18
    unsigned int _endEditingCount;	// 28 = 0x1c
    unsigned int _mainUIVisibleMs;	// 32 = 0x20
    unsigned int _openAction;	// 36 = 0x24
    NSString *_sessionUUID;	// 40 = 0x28
    _Bool _directInput;	// 48 = 0x30
    _Bool _externalInput;	// 49 = 0x31
    _Bool _secureInput;	// 50 = 0x32
    struct {
        unsigned int timestamp:1;
        unsigned int bannerVisibleMs:1;
        unsigned int beginEditingCount:1;
        unsigned int closeAction:1;
        unsigned int endEditingCount:1;
        unsigned int mainUIVisibleMs:1;
        unsigned int openAction:1;
        unsigned int directInput:1;
        unsigned int externalInput:1;
        unsigned int secureInput:1;
    } _has;	// 52 = 0x34
}

@property(nonatomic) unsigned int mainUIVisibleMs; // @synthesize mainUIVisibleMs=_mainUIVisibleMs;
@property(nonatomic) unsigned int bannerVisibleMs; // @synthesize bannerVisibleMs=_bannerVisibleMs;
@property(nonatomic) _Bool externalInput; // @synthesize externalInput=_externalInput;
@property(nonatomic) _Bool directInput; // @synthesize directInput=_directInput;
@property(nonatomic) _Bool secureInput; // @synthesize secureInput=_secureInput;
@property(nonatomic) unsigned int endEditingCount; // @synthesize endEditingCount=_endEditingCount;
@property(nonatomic) unsigned int beginEditingCount; // @synthesize beginEditingCount=_beginEditingCount;
@property(nonatomic) unsigned int closeAction; // @synthesize closeAction=_closeAction;
@property(nonatomic) unsigned int openAction; // @synthesize openAction=_openAction;
@property(retain, nonatomic) NSString *sessionUUID; // @synthesize sessionUUID=_sessionUUID;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;	// IMP=0x0000000100056c04
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100056958
- (unsigned long long)hash;	// IMP=0x0000000100056774
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100056500
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000562e0
- (void)copyTo:(id)arg1;	// IMP=0x00000001000560f8
- (void)writeTo:(id)arg1;	// IMP=0x0000000100055f3c
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100055f34
- (id)dictionaryRepresentation;	// IMP=0x000000010005524c
- (id)description;	// IMP=0x0000000100055198
@property(nonatomic) _Bool hasMainUIVisibleMs;
@property(nonatomic) _Bool hasBannerVisibleMs;
@property(nonatomic) _Bool hasExternalInput;
@property(nonatomic) _Bool hasDirectInput;
@property(nonatomic) _Bool hasSecureInput;
@property(nonatomic) _Bool hasEndEditingCount;
@property(nonatomic) _Bool hasBeginEditingCount;
@property(nonatomic) _Bool hasCloseAction;
@property(nonatomic) _Bool hasOpenAction;
@property(readonly, nonatomic) _Bool hasSessionUUID;
@property(nonatomic) _Bool hasTimestamp;

@end

