//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDActivityRequestRecord.h"

@class NSUUID, RPCompanionLinkClient;

__attribute__((visibility("hidden")))
@interface SDActivityEncryptionKeyRequestRecord : SDActivityRequestRecord
{
    NSUUID *_previousKeyIdentifier;	// 64 = 0x40
    RPCompanionLinkClient *_linkClient;	// 72 = 0x48
}

@property(retain, nonatomic) RPCompanionLinkClient *linkClient; // @synthesize linkClient=_linkClient;
@property(retain, nonatomic) NSUUID *previousKeyIdentifier; // @synthesize previousKeyIdentifier=_previousKeyIdentifier;
- (void).cxx_destruct;	// IMP=0x0000000100091360
- (id)description;	// IMP=0x00000001000911dc
- (void)dealloc;	// IMP=0x0000000100091184

@end

