//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerAppStoreLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x000000010000b89c
- (long long)transferTypes;	// IMP=0x000000010000b864
- (id)singleItemActionTitle;	// IMP=0x000000010000b858
- (_Bool)canHandleTransfer;	// IMP=0x000000010000b838
- (id)candidateIdentifiers;	// IMP=0x000000010000b758
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010000b6f0

@end

