//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandler.h"

@class LSAppLink;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerGenericLinks : SDAirDropHandler
{
    LSAppLink *_appLink;	// 8 = 0x8
}

@property(retain, nonatomic) LSAppLink *appLink; // @synthesize appLink=_appLink;
- (void).cxx_destruct;	// IMP=0x00000001001584e4
- (void)updatePossibleActions;	// IMP=0x0000000100158248
- (id)suitableContentsDescription;	// IMP=0x0000000100157fd4
- (long long)transferTypes;	// IMP=0x0000000100157f9c
- (_Bool)canHandleTransfer;	// IMP=0x0000000100157f7c

@end

