//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandler.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerPhotos : SDAirDropHandler
{
    _Bool _hasPhotos;	// 8 = 0x8
    _Bool _hasVideos;	// 9 = 0x9
    _Bool _shouldExtractImagesFromLivePhotos;	// 10 = 0xa
}

@property(readonly, nonatomic) _Bool shouldExtractImagesFromLivePhotos; // @synthesize shouldExtractImagesFromLivePhotos=_shouldExtractImagesFromLivePhotos;
- (id)createDestination;	// IMP=0x00000001000ececc
- (void)updatePossibleActions;	// IMP=0x00000001000ece98
- (id)suitableContentsDescription;	// IMP=0x00000001000ec9d4
- (long long)transferTypes;	// IMP=0x00000001000ec99c
- (_Bool)canHandleTransfer;	// IMP=0x00000001000ec97c
- (id)initWithTransfer:(id)arg1;	// IMP=0x00000001000ec914

@end

