//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerNewsLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x0000000100016ad8
- (long long)transferTypes;	// IMP=0x0000000100016aa0
- (_Bool)canHandleTransfer;	// IMP=0x0000000100016a80
- (id)candidateIdentifiers;	// IMP=0x00000001000169c4
- (id)initWithTransfer:(id)arg1;	// IMP=0x0000000100016960

@end

