//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandleriTunesStoreLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x00000001000be460
- (long long)transferTypes;	// IMP=0x00000001000be428
- (id)singleItemActionTitle;	// IMP=0x00000001000be41c
- (_Bool)canHandleTransfer;	// IMP=0x00000001000be3fc
- (id)candidateIdentifiers;	// IMP=0x00000001000be31c
- (id)initWithTransfer:(id)arg1;	// IMP=0x00000001000be29c

@end

