//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandler.h"

@class SDAirDropHandleriCloudDrive;

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerUnsupportedType : SDAirDropHandler
{
    SDAirDropHandleriCloudDrive *_icloudDriveHandler;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010017cb1c
- (void)triggerAppStoreSearch;	// IMP=0x000000010017c8d0
- (void)updatePossibleActions;	// IMP=0x000000010017c614
- (id)suitableContentsDescription;	// IMP=0x000000010017c4dc
- (_Bool)canHandleTransfer;	// IMP=0x000000010017c44c
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010017c360

@end

