//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface SDAirDropPeerMetric : NSObject
{
    NSString *_sessionID;	// 8 = 0x8
    NSString *_modelName;	// 16 = 0x10
    NSNumber *_bluetoothDiscovery;	// 24 = 0x18
    NSNumber *_bonjourDiscovery;	// 32 = 0x20
    NSNumber *_bonjourTXTRecordDiscovery;	// 40 = 0x28
    NSNumber *_bonjourResolveComplete;	// 48 = 0x30
    NSNumber *_tcpConnectionComplete;	// 56 = 0x38
    NSNumber *_tlsHandshakeComplete;	// 64 = 0x40
    NSNumber *_identityQueryComplete;	// 72 = 0x48
    NSNumber *_totalDiscovery;	// 80 = 0x50
    NSNumber *_verifiableIdentity;	// 88 = 0x58
}

@property(retain) NSNumber *verifiableIdentity; // @synthesize verifiableIdentity=_verifiableIdentity;
@property(retain) NSNumber *totalDiscovery; // @synthesize totalDiscovery=_totalDiscovery;
@property(retain) NSNumber *identityQueryComplete; // @synthesize identityQueryComplete=_identityQueryComplete;
@property(retain) NSNumber *tlsHandshakeComplete; // @synthesize tlsHandshakeComplete=_tlsHandshakeComplete;
@property(retain) NSNumber *tcpConnectionComplete; // @synthesize tcpConnectionComplete=_tcpConnectionComplete;
@property(retain) NSNumber *bonjourResolveComplete; // @synthesize bonjourResolveComplete=_bonjourResolveComplete;
@property(retain) NSNumber *bonjourTXTRecordDiscovery; // @synthesize bonjourTXTRecordDiscovery=_bonjourTXTRecordDiscovery;
@property(retain) NSNumber *bonjourDiscovery; // @synthesize bonjourDiscovery=_bonjourDiscovery;
@property(retain) NSNumber *bluetoothDiscovery; // @synthesize bluetoothDiscovery=_bluetoothDiscovery;
@property(retain) NSString *modelName; // @synthesize modelName=_modelName;
@property(retain) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;	// IMP=0x0000000100101ff0

@end

