//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandleriBooksLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x0000000100056da0
- (long long)transferTypes;	// IMP=0x0000000100056d68
- (id)singleItemActionTitle;	// IMP=0x0000000100056d5c
- (_Bool)canHandleTransfer;	// IMP=0x0000000100056d3c
- (id)candidateIdentifiers;	// IMP=0x0000000100056c80
- (id)initWithTransfer:(id)arg1;	// IMP=0x0000000100056c18

@end

