//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerFindMyFriendsLinks : SDAirDropHandlerGenericLinks
{
}

- (void)updatePossibleActions;	// IMP=0x000000010000fffc
- (id)suitableContentsDescription;	// IMP=0x000000010000fe64
- (id)suitableContentsTitle;	// IMP=0x000000010000fe58
- (long long)transferTypes;	// IMP=0x000000010000fe20
- (_Bool)canHandleTransfer;	// IMP=0x000000010000fe00
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010000fdc8

@end

