//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CFNetwork/NSMutableURLRequest.h>

__attribute__((visibility("hidden")))
@interface SDAppleIDMutableURLRequest : NSMutableURLRequest
{
}

- (id)initWithURL:(id)arg1 gsToken:(id)arg2;	// IMP=0x00000001000df9a4

@end

