//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SDAppleIDVerifiedIdentity : NSObject
{
    NSString *_accountIdentifier;	// 8 = 0x8
    NSString *_emailOrPhone;	// 16 = 0x10
}

@property(readonly, nonatomic) NSString *emailOrPhone; // @synthesize emailOrPhone=_emailOrPhone;
@property(readonly, nonatomic) NSString *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
- (void).cxx_destruct;	// IMP=0x000000010017df40
- (id)initWithAccountIdentifier:(id)arg1 emailOrPhone:(id)arg2;	// IMP=0x000000010017de6c

@end

