//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSBundle;

__attribute__((visibility("hidden")))
@interface SDASharedItemsFactory : NSObject
{
    NSBundle *_bundle;	// 8 = 0x8
    NSArray *_calendarEvents;	// 16 = 0x10
    NSArray *_contacts;	// 24 = 0x18
    NSArray *_images;	// 32 = 0x20
    NSArray *_svgImages;	// 40 = 0x28
    NSArray *_genericDataDocuments;	// 48 = 0x30
    NSArray *_pages;	// 56 = 0x38
    NSArray *_passes;	// 64 = 0x40
    NSArray *_pdfs;	// 72 = 0x48
    NSArray *_sharingDrawingDocuments;	// 80 = 0x50
    NSArray *_textDocuments;	// 88 = 0x58
    NSArray *_videos;	// 96 = 0x60
    NSArray *_voiceMemos;	// 104 = 0x68
    NSArray *_iLifeLinks;	// 112 = 0x70
    NSArray *_iTunesStoreLinks;	// 120 = 0x78
    NSArray *_iWorkLinks;	// 128 = 0x80
    NSArray *_mapsLinks;	// 136 = 0x88
    NSArray *_sharedKeynoteLiveLinks;	// 144 = 0x90
    NSArray *_sharediCloudDocumentsLinks;	// 152 = 0x98
    NSArray *_telephoneLinks;	// 160 = 0xa0
    NSArray *_webLinks;	// 168 = 0xa8
    NSArray *_webLinkStrings;	// 176 = 0xb0
    NSArray *_webLinkStringBlocks;	// 184 = 0xb8
    NSArray *_yelpLinks;	// 192 = 0xc0
    NSArray *_attributedStrings;	// 200 = 0xc8
    NSArray *_strings;	// 208 = 0xd0
}

+ (id)sharedItemsInCategory:(long long)arg1 ofType:(long long)arg2;	// IMP=0x00000001000f3f50
+ (id)plainItemsFromItemSources:(id)arg1;	// IMP=0x00000001000f3dfc
+ (id)sharedFactory;	// IMP=0x00000001000f038c
@property(retain, nonatomic) NSArray *strings; // @synthesize strings=_strings;
@property(retain, nonatomic) NSArray *attributedStrings; // @synthesize attributedStrings=_attributedStrings;
@property(retain, nonatomic) NSArray *yelpLinks; // @synthesize yelpLinks=_yelpLinks;
@property(retain, nonatomic) NSArray *webLinkStringBlocks; // @synthesize webLinkStringBlocks=_webLinkStringBlocks;
@property(retain, nonatomic) NSArray *webLinkStrings; // @synthesize webLinkStrings=_webLinkStrings;
@property(retain, nonatomic) NSArray *webLinks; // @synthesize webLinks=_webLinks;
@property(retain, nonatomic) NSArray *telephoneLinks; // @synthesize telephoneLinks=_telephoneLinks;
@property(retain, nonatomic) NSArray *sharediCloudDocumentsLinks; // @synthesize sharediCloudDocumentsLinks=_sharediCloudDocumentsLinks;
@property(retain, nonatomic) NSArray *sharedKeynoteLiveLinks; // @synthesize sharedKeynoteLiveLinks=_sharedKeynoteLiveLinks;
@property(retain, nonatomic) NSArray *mapsLinks; // @synthesize mapsLinks=_mapsLinks;
@property(retain, nonatomic) NSArray *iWorkLinks; // @synthesize iWorkLinks=_iWorkLinks;
@property(retain, nonatomic) NSArray *iTunesStoreLinks; // @synthesize iTunesStoreLinks=_iTunesStoreLinks;
@property(retain, nonatomic) NSArray *iLifeLinks; // @synthesize iLifeLinks=_iLifeLinks;
@property(retain, nonatomic) NSArray *voiceMemos; // @synthesize voiceMemos=_voiceMemos;
@property(retain, nonatomic) NSArray *videos; // @synthesize videos=_videos;
@property(retain, nonatomic) NSArray *textDocuments; // @synthesize textDocuments=_textDocuments;
@property(retain, nonatomic) NSArray *sharingDrawingDocuments; // @synthesize sharingDrawingDocuments=_sharingDrawingDocuments;
@property(retain, nonatomic) NSArray *pdfs; // @synthesize pdfs=_pdfs;
@property(retain, nonatomic) NSArray *passes; // @synthesize passes=_passes;
@property(retain, nonatomic) NSArray *pages; // @synthesize pages=_pages;
@property(retain, nonatomic) NSArray *genericDataDocuments; // @synthesize genericDataDocuments=_genericDataDocuments;
@property(retain, nonatomic) NSArray *svgImages; // @synthesize svgImages=_svgImages;
@property(retain, nonatomic) NSArray *images; // @synthesize images=_images;
@property(retain, nonatomic) NSArray *contacts; // @synthesize contacts=_contacts;
@property(retain, nonatomic) NSArray *calendarEvents; // @synthesize calendarEvents=_calendarEvents;
- (void).cxx_destruct;	// IMP=0x00000001000f529c
- (id)itemSourcesForFileNames:(id)arg1 previewImageBaseName:(id)arg2 fakeItemDuration:(float)arg3 fakeItemBytes:(long long)arg4 fakeBundleID:(id)arg5;	// IMP=0x00000001000f3984
- (id)itemSourcesForNonFileURLDictionaries:(id)arg1 fakeItemDuration:(float)arg2 fakeItemBytes:(long long)arg3 fakeBundleID:(id)arg4;	// IMP=0x00000001000f367c
- (id)keynoteLiveLinks;	// IMP=0x00000001000f1f90
- (id)findMyFriendsLink;	// IMP=0x00000001000f1bdc
- (id)dataDocuments;	// IMP=0x00000001000f1428
- (id)init;	// IMP=0x00000001000f0424

@end

