//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSError, SDAutoUnlockSessionManager, SFAutoUnlockDevice;

@protocol SDAutoUnlockSessionManagerObserver <NSObject>

@optional
- (void)session:(SDAutoUnlockSessionManager *)arg1 didFailUnlockWithResults:(NSDictionary *)arg2 error:(NSError *)arg3 incrementedAttempt:(_Bool)arg4;
- (void)session:(SDAutoUnlockSessionManager *)arg1 didCompleteUnlockWithDevice:(SFAutoUnlockDevice *)arg2;
- (void)session:(SDAutoUnlockSessionManager *)arg1 didBeginAttemptWithDevice:(SFAutoUnlockDevice *)arg2;
- (void)session:(SDAutoUnlockSessionManager *)arg1 didFailToEnableDevice:(SFAutoUnlockDevice *)arg2 error:(NSError *)arg3;
- (void)session:(SDAutoUnlockSessionManager *)arg1 didEnableWithDevice:(SFAutoUnlockDevice *)arg2;
- (void)session:(SDAutoUnlockSessionManager *)arg1 didReceiveKeyDeviceLocked:(SFAutoUnlockDevice *)arg2;
@end

