//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, _CLRangingPeer;

__attribute__((visibility("hidden")))
@interface SDAutoUnlockRangingPeer : NSObject
{
    _CLRangingPeer *_clRangingPeer;	// 8 = 0x8
    NSData *_macAddressData;	// 16 = 0x10
}

@property(retain, nonatomic) NSData *macAddressData; // @synthesize macAddressData=_macAddressData;
@property(retain, nonatomic) _CLRangingPeer *clRangingPeer; // @synthesize clRangingPeer=_clRangingPeer;
- (void).cxx_destruct;	// IMP=0x00000001000873c0

@end

