//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSUUID, RPIdentity;

__attribute__((visibility("hidden")))
@interface SDBLEIdentifiedDevice : NSObject
{
    NSData *_authTag;	// 8 = 0x8
    NSData *_btAddr;	// 16 = 0x10
    unsigned long long _discoveryFlags;	// 24 = 0x18
    NSUUID *_identifier;	// 32 = 0x20
    RPIdentity *_identity;	// 40 = 0x28
    unsigned long long _lastUpdateTicks;	// 48 = 0x30
}

@property(nonatomic) unsigned long long lastUpdateTicks; // @synthesize lastUpdateTicks=_lastUpdateTicks;
@property(retain, nonatomic) RPIdentity *identity; // @synthesize identity=_identity;
@property(retain, nonatomic) NSUUID *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) unsigned long long discoveryFlags; // @synthesize discoveryFlags=_discoveryFlags;
@property(copy, nonatomic) NSData *btAddr; // @synthesize btAddr=_btAddr;
@property(copy, nonatomic) NSData *authTag; // @synthesize authTag=_authTag;
- (void).cxx_destruct;	// IMP=0x00000001001aacb0

@end

