//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSNetServiceBrowserDelegate-Protocol.h"
#import "NSStreamDelegate-Protocol.h"
#import "SDStreamHandlerDelegate-Protocol.h"

@class NSData, NSFileHandle, NSInputStream, NSMutableData, NSNetServiceBrowser, NSOutputStream, NSString, SDStreamHandler;
@protocol OS_dispatch_queue, SDCompanionStreamDelegate;

__attribute__((visibility("hidden")))
@interface SDCompanionStream : NSObject <NSStreamDelegate, NSNetServiceBrowserDelegate, SDStreamHandlerDelegate>
{
    _Bool _initiator;	// 8 = 0x8
    _Bool _shouldStop;	// 9 = 0x9
    _Bool _clientSent;	// 10 = 0xa
    _Bool _clientReceived;	// 11 = 0xb
    _Bool _networkBufferSpaceAvailable;	// 12 = 0xc
    NSFileHandle *_fileHandle;	// 16 = 0x10
    id <SDCompanionStreamDelegate> _delegate;	// 24 = 0x18
    NSString *_identifier;	// 32 = 0x20
    SDStreamHandler *_streamHandler;	// 40 = 0x28
    NSData *_authorData;	// 48 = 0x30
    NSNetServiceBrowser *_netServiceBrowser;	// 56 = 0x38
    NSInputStream *_clientInputStream;	// 64 = 0x40
    NSOutputStream *_clientOutputStream;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_writeQueue;	// 80 = 0x50
    NSMutableData *_networkStreamData;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_readQueue;	// 96 = 0x60
    NSMutableData *_clientStreamData;	// 104 = 0x68
    long long _readFromClient;	// 112 = 0x70
    long long _wroteToClient;	// 120 = 0x78
    CDUnknownBlockType _streamsRequestHandler;	// 128 = 0x80
}

@property(copy) CDUnknownBlockType streamsRequestHandler; // @synthesize streamsRequestHandler=_streamsRequestHandler;
@property long long wroteToClient; // @synthesize wroteToClient=_wroteToClient;
@property long long readFromClient; // @synthesize readFromClient=_readFromClient;
@property(retain) NSMutableData *clientStreamData; // @synthesize clientStreamData=_clientStreamData;
@property(retain) NSObject<OS_dispatch_queue> *readQueue; // @synthesize readQueue=_readQueue;
@property(retain) NSMutableData *networkStreamData; // @synthesize networkStreamData=_networkStreamData;
@property(retain) NSObject<OS_dispatch_queue> *writeQueue; // @synthesize writeQueue=_writeQueue;
@property(retain) NSOutputStream *clientOutputStream; // @synthesize clientOutputStream=_clientOutputStream;
@property(retain) NSInputStream *clientInputStream; // @synthesize clientInputStream=_clientInputStream;
@property(retain) NSNetServiceBrowser *netServiceBrowser; // @synthesize netServiceBrowser=_netServiceBrowser;
@property _Bool networkBufferSpaceAvailable; // @synthesize networkBufferSpaceAvailable=_networkBufferSpaceAvailable;
@property _Bool clientReceived; // @synthesize clientReceived=_clientReceived;
@property _Bool clientSent; // @synthesize clientSent=_clientSent;
@property _Bool shouldStop; // @synthesize shouldStop=_shouldStop;
@property _Bool initiator; // @synthesize initiator=_initiator;
@property(retain) NSData *authorData; // @synthesize authorData=_authorData;
@property(retain) SDStreamHandler *streamHandler; // @synthesize streamHandler=_streamHandler;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
@property __weak id <SDCompanionStreamDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100067c28
- (void)logClientReceived;	// IMP=0x0000000100067950
- (void)logClientSent;	// IMP=0x00000001000678d4
- (void)writeNetworkStream;	// IMP=0x0000000100067784
- (void)readClientStream;	// IMP=0x0000000100067520
- (void)writeClientStream;	// IMP=0x0000000100067194
- (void)handleOpenedStream;	// IMP=0x00000001000670e4
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;	// IMP=0x0000000100066e5c
- (void)streamHandlerDidClose:(id)arg1 withError:(id)arg2;	// IMP=0x0000000100066bd0
- (void)streamHandler:(id)arg1 didReceiveStreamData:(id)arg2;	// IMP=0x0000000100066b4c
- (void)streamHandler:(id)arg1 bufferSpaceChanged:(_Bool)arg2;	// IMP=0x0000000100066ac0
- (void)handleStreamResponse:(id)arg1;	// IMP=0x00000001000668c0
- (void)handleStreamRequest:(id)arg1;	// IMP=0x00000001000665f0
- (void)streamHandler:(id)arg1 didReceiveMessage:(id)arg2;	// IMP=0x00000001000663c4
- (void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(_Bool)arg3;	// IMP=0x000000010006630c
- (int)setBufferSize:(int)arg1 socket:(int)arg2;	// IMP=0x00000001000662a8
@property(readonly) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
- (void)notifyStreamRequestWithError:(id)arg1;	// IMP=0x0000000100065cb0
- (void)switchToStreaming;	// IMP=0x0000000100065c14
- (void)sendInitialResponse:(_Bool)arg1;	// IMP=0x00000001000658a0
- (void)sendInitialRequest;	// IMP=0x00000001000654dc
- (void)startBrowser;	// IMP=0x00000001000653e4
- (void)getStreamsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100065370
- (void)setBundleID:(id)arg1;	// IMP=0x00000001000652b4
- (void)stopIfReady;	// IMP=0x0000000100065254
- (void)stop;	// IMP=0x0000000100065050
- (void)start;	// IMP=0x000000010006500c
- (void)dealloc;	// IMP=0x0000000100064fc0
- (id)initWithAuthorData:(id)arg1 streamHandler:(id)arg2;	// IMP=0x0000000100064e28
- (id)initWithStreamHandler:(id)arg1;	// IMP=0x0000000100064e14

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

