//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSNetServiceBrowserDelegate-Protocol.h"

@class NSMutableSet, NSNetServiceBrowser, NSString;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SDDomainBrowser : NSObject <NSNetServiceBrowserDelegate>
{
    int _clientCount;	// 8 = 0x8
    _Bool _sendNotification;	// 12 = 0xc
    NSMutableSet *_domains;	// 16 = 0x10
    NSObject<OS_dispatch_source> *_timer;	// 24 = 0x18
    struct __CFDictionary *_domainTree;	// 32 = 0x20
    NSNetServiceBrowser *_domainBrowser;	// 40 = 0x28
}

+ (id)sharedBrowser;	// IMP=0x0000000100053e50
- (void).cxx_destruct;	// IMP=0x0000000100054d1c
- (void)stop;	// IMP=0x0000000100054c4c
- (void)start;	// IMP=0x0000000100054b04
- (void)netServiceBrowser:(id)arg1 didNotSearch:(id)arg2;	// IMP=0x0000000100054a4c
- (void)netServiceBrowser:(id)arg1 didRemoveDomain:(id)arg2 moreComing:(_Bool)arg3;	// IMP=0x00000001000549e4
- (void)netServiceBrowser:(id)arg1 didFindDomain:(id)arg2 moreComing:(_Bool)arg3;	// IMP=0x000000010005492c
- (void)postNotification;	// IMP=0x00000001000548bc
- (void)buildNodes;	// IMP=0x0000000100054764
- (void)parseDomain:(id)arg1;	// IMP=0x00000001000543d0
- (id)displayNameForDomain:(id)arg1;	// IMP=0x00000001000541a4
- (id)childrenForNode:(struct __SFNode *)arg1;	// IMP=0x00000001000540e8
- (void)restart;	// IMP=0x0000000100054064
- (void)scheduleBrowser;	// IMP=0x0000000100053ff0
- (void)statusChanged:(id)arg1;	// IMP=0x0000000100053fdc
- (void)browseAfterDelay:(double)arg1;	// IMP=0x0000000100053fac
- (id)init;	// IMP=0x0000000100053ed0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

