//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

__attribute__((visibility("hidden")))
@interface SDManagedBrowser : NSObject
{
    int _clientCount;	// 8 = 0x8
    _Bool _sendNotification;	// 12 = 0xc
    NSDictionary *_servers;	// 16 = 0x10
}

+ (id)sharedBrowser;	// IMP=0x0000000100087d38
- (void).cxx_destruct;	// IMP=0x0000000100087f70
- (void)stop;	// IMP=0x0000000100087f3c
- (void)start;	// IMP=0x0000000100087eb8
- (void)buildNodesAndNotify;	// IMP=0x0000000100087eb4
@property(readonly, copy) NSArray *nodes;
- (void)setServers:(id)arg1;	// IMP=0x0000000100087e2c
- (id)init;	// IMP=0x0000000100087db8

@end

