//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDAirDropConnectionDelegate-Protocol.h"
#import "SDAirDropControllerDelegate-Protocol.h"
#import "SDAirDropInformationDelegate-Protocol.h"
#import "SDAirDropServerDelegate-Protocol.h"
#import "SDAirDropSessionDelegate-Protocol.h"
#import "SDNetworkEjecterDelegate-Protocol.h"
#import "SDNetworkResolverDelegate-Protocol.h"
#import "_TtP8sharingd23SDAirDropStatusDelegate_-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;
@protocol OS_os_transaction, OS_xpc_object, SDNetworkOperationDelegate;

__attribute__((visibility("hidden")))
@interface SDNetworkOperation : NSObject <SDAirDropServerDelegate, SDAirDropConnectionDelegate, SDAirDropSessionDelegate, SDAirDropControllerDelegate, _TtP8sharingd23SDAirDropStatusDelegate_, SDAirDropInformationDelegate, SDNetworkResolverDelegate, SDNetworkEjecterDelegate>
{
    id _operation;	// 8 = 0x8
    _Bool _connectionScheduled;	// 16 = 0x10
    NSObject<OS_xpc_object> *_connection;	// 24 = 0x18
    NSMutableDictionary *_properties;	// 32 = 0x20
    NSObject<OS_os_transaction> *_transaction;	// 40 = 0x28
    NSString *_kind;	// 48 = 0x30
    NSString *_objectKey;	// 56 = 0x38
    NSObject<OS_xpc_object> *_boostMessage;	// 64 = 0x40
    NSMutableArray *_activities;	// 72 = 0x48
    id <SDNetworkOperationDelegate> _delegate;	// 80 = 0x50
}

@property __weak id <SDNetworkOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
@property(retain) NSMutableArray *activities; // @synthesize activities=_activities;
@property(retain) NSObject<OS_xpc_object> *boostMessage; // @synthesize boostMessage=_boostMessage;
@property(copy) NSString *objectKey; // @synthesize objectKey=_objectKey;
@property(readonly, copy) NSString *kind; // @synthesize kind=_kind;
- (void).cxx_destruct;	// IMP=0x00000001000a23cc
@property(readonly, copy) NSString *description;
- (void)invalidate;	// IMP=0x00000001000a20a8
- (void)resume;	// IMP=0x00000001000a14c8
- (void)notifyClientWithPosixError:(long long)arg1;	// IMP=0x00000001000a1360
- (void)airDropConnection:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001000a12f0
- (void)networkResolver:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001000a1280
- (void)networkEjecter:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001000a1210
- (void)airDropServer:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001000a11a0
- (void)airDropSession:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001000a1130
- (void)airDropController:(id)arg1 didChange:(id)arg2;	// IMP=0x00000001000a10c4
- (void)airDropInformation:(id)arg1 didChange:(id)arg2;	// IMP=0x00000001000a1058
- (void)airDropStatus:(id)arg1 didChange:(id)arg2;	// IMP=0x00000001000a0fec
- (const void *)copyPropertyForKey:(id)arg1;	// IMP=0x00000001000a0f60
- (void)setProperty:(void *)arg1 forKey:(id)arg2;	// IMP=0x00000001000a0e68
- (void)dealloc;	// IMP=0x00000001000a0e1c
- (id)initWithKind:(id)arg1;	// IMP=0x00000001000a0cec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

