//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSMutableArray, NSString;
@protocol OS_dispatch_queue, OS_xpc_object;

__attribute__((visibility("hidden")))
@interface SDNearbyIDSAgent : NSObject <IDSServiceDelegate>
{
    _Bool _collectingSysdiagnose;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_sysdiagnoseQueue;	// 24 = 0x18
    NSMutableArray *_receivedHoneybeeIDs;	// 32 = 0x20
    IDSService *_idsService;	// 40 = 0x28
    NSObject<OS_xpc_object> *_honeybeeConnection;	// 48 = 0x30
}

+ (id)sharedAgent;	// IMP=0x00000001000ee6f4
@property(retain, nonatomic) NSObject<OS_xpc_object> *honeybeeConnection; // @synthesize honeybeeConnection=_honeybeeConnection;
@property(readonly, nonatomic) IDSService *idsService; // @synthesize idsService=_idsService;
@property(retain, nonatomic) NSMutableArray *receivedHoneybeeIDs; // @synthesize receivedHoneybeeIDs=_receivedHoneybeeIDs;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sysdiagnoseQueue; // @synthesize sysdiagnoseQueue=_sysdiagnoseQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(nonatomic) _Bool collectingSysdiagnose; // @synthesize collectingSysdiagnose=_collectingSysdiagnose;
- (void).cxx_destruct;	// IMP=0x00000001000f00d8
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x00000001000efdd4
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5 context:(id)arg6;	// IMP=0x00000001000efccc
- (void)_sendMessage:(id)arg1 devices:(id)arg2 type:(long long)arg3;	// IMP=0x00000001000ef880
- (void)_uploadSysdiagnoseToHoneybee:(id)arg1 honeybeeID:(id)arg2;	// IMP=0x00000001000ef6ec
- (void)_uploadSysdiagnose:(id)arg1;	// IMP=0x00000001000ef570
- (void)_collectSysdiagnoseWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000ef140
- (void)_handleLogRequest:(id)arg1;	// IMP=0x00000001000eeea8
- (void)_sendLogRequestToDevices:(id)arg1 honeybeeID:(id)arg2;	// IMP=0x00000001000eed64
- (void)sendLogRequestToDevices:(id)arg1 honeybeeID:(id)arg2;	// IMP=0x00000001000eec68
- (void)_sendLogRequestToDeviceID:(id)arg1 honeybeeID:(id)arg2;	// IMP=0x00000001000ee990
- (void)sendLogRequestToDeviceIDs:(id)arg1 honeybeeID:(id)arg2;	// IMP=0x00000001000ee894
- (id)init;	// IMP=0x00000001000ee774

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

