//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDXPCDaemon.h"

#import "IDSServiceDelegate-Protocol.h"
#import "SFPairedDeviceDaemonInterface-Protocol.h"

@class CUCoalescer, IDSDevice, IDSService, NSDate, NSDictionary, NSMutableArray, NSNumber, NSObject, NSString, RPCompanionLinkClient, SFBLEPipe, SFPowerSource, SFPowerSourceMonitor;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SDPairedDeviceAgent : SDXPCDaemon <IDSServiceDelegate, SFPairedDeviceDaemonInterface>
{
    _Bool _activateCalled;	// 8 = 0x8
    _Bool _invalidateCalled;	// 9 = 0x9
    NSDate *_animationDateReceived;	// 16 = 0x10
    NSDate *_animationDateForIDS;	// 24 = 0x18
    NSDate *_animationDateToSend;	// 32 = 0x20
    _Bool _animationDateSupported;	// 40 = 0x28
    NSNumber *_animationMessageID;	// 48 = 0x30
    SFBLEPipe *_blePipe;	// 56 = 0x38
    RPCompanionLinkClient *_companionLinkClient;	// 64 = 0x40
    CDUnknownBlockType _chargingUIHandler;	// 72 = 0x48
    CUCoalescer *_idsConnectionCoalescer;	// 80 = 0x50
    IDSDevice *_idsConnectedDevice;	// 88 = 0x58
    IDSService *_idsService;	// 96 = 0x60
    CUCoalescer *_idsSyncCoalescer;	// 104 = 0x68
    NSObject<OS_dispatch_source> *_idsInfoTimer;	// 112 = 0x70
    _Bool _infoRequestForced;	// 120 = 0x78
    int _lockStatePairedDevice;	// 124 = 0x7c
    NSMutableArray *_messageIDs;	// 128 = 0x80
    struct NSMutableDictionary *_nrRegisteredDevices;	// 136 = 0x88
    SFPowerSource *_powerSourceLocal;	// 144 = 0x90
    NSDictionary *_powerSourceMessage;	// 152 = 0x98
    SFPowerSourceMonitor *_powerSourceMonitor;	// 160 = 0xa0
    SFPowerSource *_powerSourcePairedDevice;	// 168 = 0xa8
    _Bool _powerSourceWasCharging;	// 176 = 0xb0
    int _testingChargingToken;	// 180 = 0xb4
    _Bool _uiShowing;	// 184 = 0xb8
    long long _wristStateLocal;	// 192 = 0xc0
    long long _wristStatePairedDevice;	// 200 = 0xc8
}

+ (id)sharedAgent;	// IMP=0x0000000100118ba0
- (void).cxx_destruct;	// IMP=0x000000010011f018
- (void)sendDashboardEntryWithName:(id)arg1 dict:(id)arg2;	// IMP=0x000000010011eea0
- (void)sendDismissUIWithReason:(long long)arg1;	// IMP=0x000000010011ee68
- (void)triggerChargingUIWithDismissHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010011ec40
- (void)sendAnimationDate:(id)arg1;	// IMP=0x000000010011ec08
- (void)requestAnimationDateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010011ebec
- (void)initialViewControllerDidDisappear;	// IMP=0x000000010011eb4c
- (void)initialViewControllerDidAppear;	// IMP=0x000000010011eaa8
- (void)connectionInvalidated:(id)arg1;	// IMP=0x000000010011e9c4
- (void)connectionEstablished:(id)arg1;	// IMP=0x000000010011e8e0
- (_Bool)shouldAcceptNewConnection:(id)arg1;	// IMP=0x000000010011e8d8
- (id)remoteObjectInterface;	// IMP=0x000000010011e8bc
- (id)exportedInterface;	// IMP=0x000000010011e8a0
- (id)machServiceName;	// IMP=0x000000010011e874
- (void)_wristStateUpdate:(long long)arg1;	// IMP=0x000000010011e7cc
- (void)_wristStateHandleMessage:(id)arg1;	// IMP=0x000000010011e6b4
- (void)_wristStateChanged;	// IMP=0x000000010011e5c0
- (void)wristStateChanged:(id)arg1;	// IMP=0x000000010011e4e4
@property(readonly, nonatomic) long long wristState;
- (void)_testingOnCharger;	// IMP=0x000000010011e43c
- (void)_testingUnregisterNotifications;	// IMP=0x000000010011e40c
- (void)_testingRegisterNotifications;	// IMP=0x000000010011e3d4
- (void)_disablePowerStateMonitor;	// IMP=0x000000010011e374
- (void)_setupWristStateMonitor;	// IMP=0x000000010011e2e8
- (void)_setupPowerSourceMonitor;	// IMP=0x000000010011dcd8
- (void)_setupLockStateMonitor;	// IMP=0x000000010011dc4c
- (void)_systemStateUnregisterObservers;	// IMP=0x000000010011dbc8
- (void)_systemStateRegisterObservers;	// IMP=0x000000010011db7c
- (void)_powerSourceUpdatePairedDeviceInfo:(id)arg1;	// IMP=0x000000010011d3ac
- (void)_powerSourceLost:(id)arg1;	// IMP=0x000000010011d278
- (void)_powerSourceChanged:(id)arg1;	// IMP=0x000000010011cf28
- (void)_nanoRegistryUnregisterChanges;	// IMP=0x000000010011cd8c
- (void)_nanoRegistryRegisterChangesForDevice:(id)arg1;	// IMP=0x000000010011c838
- (void)_messageIDRemove:(id)arg1;	// IMP=0x000000010011c6a0
- (void)_messageIDAdd:(id)arg1;	// IMP=0x000000010011c500
- (id)_messageFromPowerSource:(id)arg1;	// IMP=0x000000010011c200
- (void)_messageHandleDashboardEntry:(id)arg1;	// IMP=0x000000010011bfa4
- (void)_messageHandlePowerSourceUpdate:(id)arg1;	// IMP=0x000000010011be94
- (void)_messageHandleAllUpdate:(id)arg1;	// IMP=0x000000010011bbf4
- (void)_messageHandleIncomingData:(id)arg1;	// IMP=0x000000010011b8ac
- (void)_lockStateUpdate:(int)arg1;	// IMP=0x000000010011b804
- (void)_lockStateHandleMessage:(id)arg1;	// IMP=0x000000010011b6ec
- (void)_lockStateChanged:(id)arg1;	// IMP=0x000000010011b610
@property(readonly, nonatomic) int lockState;
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;	// IMP=0x000000010011b524
- (void)service:(id)arg1 devicesChanged:(id)arg2;	// IMP=0x000000010011b448
- (void)service:(id)arg1 connectedDevicesChanged:(id)arg2;	// IMP=0x000000010011b36c
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x000000010011b190
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5 context:(id)arg6;	// IMP=0x000000010011afe8
- (void)_idsUpdateConnectedState;	// IMP=0x000000010011aa04
- (void)_idsTriggerSyncForAnimation:(_Bool)arg1;	// IMP=0x000000010011a954
- (void)_idsTriggerSync;	// IMP=0x000000010011a944
- (void)_idsTimerInfoInvalidate;	// IMP=0x000000010011a88c
- (void)_idsTimerInfoFired;	// IMP=0x000000010011a7c4
- (void)_idsTimerInfoRestart;	// IMP=0x000000010011a648
- (void)_idsSendDashboardEntryToCompanion:(id)arg1;	// IMP=0x000000010011a644
- (void)_idsSendStateUpdate:(id)arg1;	// IMP=0x000000010011a0a8
- (_Bool)_idsHasDefaultDevice;	// IMP=0x0000000100119f60
- (void)_idsEnsureSynced;	// IMP=0x0000000100119e68
- (void)_idsEnsureCoalescersStopped;	// IMP=0x0000000100119e00
- (void)_idsEnsureCoalescersStarted;	// IMP=0x0000000100119af0
- (id)_idsActiveDevice;	// IMP=0x000000010011999c
- (void)_companionLinkRegisterEvents;	// IMP=0x0000000100119998
- (void)_companionLinkDevicesChanged;	// IMP=0x0000000100119894
- (_Bool)_companionLinkConnected;	// IMP=0x00000001001196c0
- (void)_companionLinkDisable;	// IMP=0x0000000100119684
- (void)_companionLinkEnable;	// IMP=0x00000001001192a4
- (id)_queueWithFallbackQOS;	// IMP=0x0000000100119244
- (void)_invalidate;	// IMP=0x00000001001190ac
- (void)invalidate;	// IMP=0x0000000100119020
- (void)_activate;	// IMP=0x0000000100118dd0
- (void)activate;	// IMP=0x0000000100118d44
- (id)init;	// IMP=0x0000000100118c20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

