//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, SDUnlockIDSController;

@protocol SDUnlockIDSControllerDelegate <NSObject>

@optional
- (void)idsControllerSpaceDidBecomeAvailable:(SDUnlockIDSController *)arg1;
- (void)idsControllerNearbyStateChanged:(SDUnlockIDSController *)arg1;
- (void)idsController:(SDUnlockIDSController *)arg1 didReceiveProtoData:(NSData *)arg2 forType:(unsigned short)arg3;
@end

