//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

__attribute__((visibility("hidden")))
@interface SDUnlockSessionRecord : NSObject
{
    NSData *_keyData;	// 8 = 0x8
    long long _unlockSessionID;	// 16 = 0x10
    unsigned long long _expireTime;	// 24 = 0x18
}

@property unsigned long long expireTime; // @synthesize expireTime=_expireTime;
@property long long unlockSessionID; // @synthesize unlockSessionID=_unlockSessionID;
@property(retain) NSData *keyData; // @synthesize keyData=_keyData;
- (void).cxx_destruct;	// IMP=0x000000010016f06c
- (id)description;	// IMP=0x000000010016ef60

@end

