//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SDUnlockSessionManager.h"

#import "SDUnlockIDSControllerDelegate-Protocol.h"

@class NSObject, NSString, NSTimer, SDUnlockSessionRecord;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SDUnlockKeyManager : SDUnlockSessionManager <SDUnlockIDSControllerDelegate>
{
    _Bool _useEscrowRecord;	// 8 = 0x8
    _Bool _remoteDeviceLocked;	// 9 = 0x9
    _Bool _ltkWaitingForUnlock;	// 10 = 0xa
    _Bool _outstandingStartLTK;	// 11 = 0xb
    _Bool _unlockingForKeybagUnlock;	// 12 = 0xc
    long long _unlockingState;	// 16 = 0x10
    NSTimer *_stashTimer;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_stateTimer;	// 32 = 0x20
    NSObject<OS_dispatch_source> *_longTermKeyTimer;	// 40 = 0x28
    SDUnlockSessionRecord *_sessionRecord;	// 48 = 0x30
    CDUnknownBlockType _stashHandler;	// 56 = 0x38
    CDUnknownBlockType _stateHandler;	// 64 = 0x40
    id _keybagAssertion;	// 72 = 0x48
}

+ (id)sharedKeyManager;	// IMP=0x000000010016f080
@property(retain) id keybagAssertion; // @synthesize keybagAssertion=_keybagAssertion;
@property(copy) CDUnknownBlockType stateHandler; // @synthesize stateHandler=_stateHandler;
@property(copy) CDUnknownBlockType stashHandler; // @synthesize stashHandler=_stashHandler;
@property(retain) SDUnlockSessionRecord *sessionRecord; // @synthesize sessionRecord=_sessionRecord;
@property(retain) NSObject<OS_dispatch_source> *longTermKeyTimer; // @synthesize longTermKeyTimer=_longTermKeyTimer;
@property(retain) NSObject<OS_dispatch_source> *stateTimer; // @synthesize stateTimer=_stateTimer;
@property _Bool unlockingForKeybagUnlock; // @synthesize unlockingForKeybagUnlock=_unlockingForKeybagUnlock;
@property _Bool outstandingStartLTK; // @synthesize outstandingStartLTK=_outstandingStartLTK;
@property _Bool ltkWaitingForUnlock; // @synthesize ltkWaitingForUnlock=_ltkWaitingForUnlock;
@property _Bool remoteDeviceLocked; // @synthesize remoteDeviceLocked=_remoteDeviceLocked;
@property(retain) NSTimer *stashTimer; // @synthesize stashTimer=_stashTimer;
@property _Bool useEscrowRecord; // @synthesize useEscrowRecord=_useEscrowRecord;
- (void).cxx_destruct;	// IMP=0x0000000100176674
- (_Bool)initiateStashBagCreation;	// IMP=0x000000010017638c
- (void)initiateRemoteUnlock;	// IMP=0x0000000100175bf0
- (void)sendStateRequest;	// IMP=0x0000000100175914
- (void)sendStashToken:(id)arg1 sessionID:(unsigned int)arg2;	// IMP=0x000000010017566c
- (void)sendStashKeyRequest:(id)arg1 sessionID:(unsigned int)arg2;	// IMP=0x00000001001753c4
- (void)sendSessionAuthenticationToken:(id)arg1 sessionID:(unsigned int)arg2;	// IMP=0x00000001001751dc
- (void)sendSessionKeyExchangeRequest:(id)arg1 usedEscrow:(_Bool)arg2 sessionID:(unsigned int)arg3;	// IMP=0x0000000100175004
- (void)sendSetupCreateEscrowRecordWithSessionID:(unsigned int)arg1 stepData:(id)arg2 errorCode:(long long)arg3;	// IMP=0x0000000100174e40
- (void)sendSetupSessionCreatedWithLocalKey:(id)arg1 stepData:(id)arg2 sessionID:(unsigned int)arg3 errorCode:(long long)arg4;	// IMP=0x0000000100174c44
- (void)sendClassALongTermKeyResponse:(id)arg1 sessionID:(unsigned int)arg2 errorCode:(unsigned int)arg3;	// IMP=0x0000000100174a74
- (void)sendLongTermKeyResponse:(id)arg1 requestID:(id)arg2;	// IMP=0x000000010017481c
- (void)sendStartLTKTransfer;	// IMP=0x00000001001745bc
- (void)handleUnlockStateResponse:(id)arg1;	// IMP=0x0000000100174250
- (void)handleStashConfirmation:(id)arg1;	// IMP=0x00000001001740ac
- (void)handleStashKeyExchangeResponse:(id)arg1;	// IMP=0x0000000100173d04
- (void)handleResetState:(id)arg1;	// IMP=0x0000000100173c3c
- (void)handleUnlockConfirmation:(id)arg1;	// IMP=0x000000010017393c
- (void)handleSessionKeyExchangeResponse:(id)arg1;	// IMP=0x0000000100173410
- (void)handleCreateEscrowSecret:(id)arg1;	// IMP=0x0000000100172f48
- (void)handleEscrowSessionRequest:(unsigned int)arg1 withUpdatedLongTermKey:(_Bool)arg2;	// IMP=0x0000000100172bd0
- (void)handleSetupRequest:(id)arg1;	// IMP=0x00000001001728e8
- (_Bool)updateLongTermKey:(id)arg1;	// IMP=0x00000001001727ac
- (void)handleClassALongTermKeyRequest:(id)arg1;	// IMP=0x00000001001724b0
- (void)handleLongTermKeyRequest:(id)arg1;	// IMP=0x000000010017213c
- (void)handleRemoteLockStateChanged:(id)arg1;	// IMP=0x0000000100171e40
- (void)idsControllerNearbyStateChanged:(id)arg1;	// IMP=0x0000000100171dc8
- (void)idsController:(id)arg1 didReceiveProtoData:(id)arg2 forType:(unsigned short)arg3;	// IMP=0x0000000100171be4
- (id)stringForState:(long long)arg1;	// IMP=0x0000000100171b80
@property long long unlockingState; // @synthesize unlockingState=_unlockingState;
- (void)resetState;	// IMP=0x00000001001719b8
- (void)resetAndClearState;	// IMP=0x0000000100171974
- (void)resetSetupState;	// IMP=0x0000000100171930
- (void)notifyStashStateWithError:(id)arg1;	// IMP=0x000000010017181c
- (void)establishStashBagWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100171594
- (void)invalidateStashTimer;	// IMP=0x0000000100171548
- (void)stashTimerFired:(id)arg1;	// IMP=0x0000000100171438
- (void)restartStashTimer;	// IMP=0x00000001001713c0
- (void)invalidateStateTimer;	// IMP=0x0000000100171330
- (void)restartStateTimer;	// IMP=0x00000001001710c8
- (void)notifyUnlockStateWithState:(id)arg1 error:(id)arg2;	// IMP=0x0000000100171054
- (void)unlockStateForDevice:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100170ef0
- (void)syncUnlockEnabled:(_Bool)arg1;	// IMP=0x0000000100170dfc
- (_Bool)unlockEnabled;	// IMP=0x0000000100170d80
- (void)disableUnlockPairingForSecurityManager:(id)arg1;	// IMP=0x0000000100170cbc
- (void)disableUnlockPairing;	// IMP=0x0000000100170cac
- (void)checkDevicePairingState;	// IMP=0x0000000100170b74
- (void)handleActiveDeviceUpdated;	// IMP=0x0000000100170b18
- (void)releaseKeyBagAssertion;	// IMP=0x0000000100170a94
- (void)takeMobileKeybagAssertion;	// IMP=0x000000010017092c
- (void)invalidateLongTermKeyTimer;	// IMP=0x000000010017089c
- (void)restartLongTermKeyTimer:(unsigned long long)arg1;	// IMP=0x00000001001706f8
- (void)newDeviceBecameActive:(id)arg1;	// IMP=0x0000000100170614
- (void)devicesDidFailToPair:(id)arg1;	// IMP=0x00000001001702c8
- (void)devicesDidUnpair:(id)arg1;	// IMP=0x000000010016ff7c
- (_Bool)startUnlockIfNeeded;	// IMP=0x000000010016fe90
- (void)handleUILockStateChange;	// IMP=0x000000010016fcec
- (void)keyBagLockStateChange:(id)arg1;	// IMP=0x000000010016fb3c
- (void)startLTKExchange;	// IMP=0x000000010016faf8
- (void)handleConfigState;	// IMP=0x000000010016fa20
- (void)deviceDidEnterConfigurationState:(id)arg1;	// IMP=0x000000010016f8a4
- (id)generateDebugInfo;	// IMP=0x000000010016f610
- (void)debugInfoRequested:(id)arg1;	// IMP=0x000000010016f5a4
- (void)addObservers;	// IMP=0x000000010016f384
- (id)init;	// IMP=0x000000010016f100

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

