//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData;

@interface SDUnlockSetupCreateSecret : PBCodable <NSCopying>
{
    unsigned int _sessionID;	// 8 = 0x8
    NSData *_token;	// 16 = 0x10
    unsigned int _version;	// 24 = 0x18
    CDStruct_6358cc24 _has;	// 28 = 0x1c
}

@property(retain, nonatomic) NSData *token; // @synthesize token=_token;
@property(nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void).cxx_destruct;	// IMP=0x000000010004d850
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010004d770
- (unsigned long long)hash;	// IMP=0x000000010004d6dc
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010004d5d4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010004d500
- (void)copyTo:(id)arg1;	// IMP=0x000000010004d464
- (void)writeTo:(id)arg1;	// IMP=0x000000010004d3cc
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010004d3c4
- (id)dictionaryRepresentation;	// IMP=0x000000010004cf7c
- (id)description;	// IMP=0x000000010004cec8
@property(readonly, nonatomic) _Bool hasToken;
@property(nonatomic) _Bool hasSessionID;
@property(nonatomic) _Bool hasVersion;

@end

