//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface SDUnlockSessionConfirmation : PBCodable <NSCopying>
{
    unsigned int _sessionID;	// 8 = 0x8
    unsigned int _version;	// 12 = 0xc
    _Bool _success;	// 16 = 0x10
    _Bool _supportsACK;	// 17 = 0x11
    struct {
        unsigned int sessionID:1;
        unsigned int version:1;
        unsigned int success:1;
        unsigned int supportsACK:1;
    } _has;	// 20 = 0x14
}

@property(nonatomic) _Bool supportsACK; // @synthesize supportsACK=_supportsACK;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(nonatomic) unsigned int sessionID; // @synthesize sessionID=_sessionID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010012bfa4
- (unsigned long long)hash;	// IMP=0x000000010012bef0
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010012bdb4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010012bcc4
- (void)copyTo:(id)arg1;	// IMP=0x000000010012bbf8
- (void)writeTo:(id)arg1;	// IMP=0x000000010012bb2c
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010012bb24
- (id)dictionaryRepresentation;	// IMP=0x000000010012b4e8
- (id)description;	// IMP=0x000000010012b434
@property(nonatomic) _Bool hasSupportsACK;
@property(nonatomic) _Bool hasSuccess;
@property(nonatomic) _Bool hasSessionID;
@property(nonatomic) _Bool hasVersion;

@end

