//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SDUnlockDisable : PBCodable <NSCopying>
{
    NSString *_pairingID;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

@property(retain, nonatomic) NSString *pairingID; // @synthesize pairingID=_pairingID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void).cxx_destruct;	// IMP=0x000000010001fcfc
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010001fc50
- (unsigned long long)hash;	// IMP=0x000000010001fbe4
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010001fb04
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010001fa54
- (void)copyTo:(id)arg1;	// IMP=0x000000010001f9dc
- (void)writeTo:(id)arg1;	// IMP=0x000000010001f96c
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010001f964
- (id)dictionaryRepresentation;	// IMP=0x000000010001f62c
- (id)description;	// IMP=0x000000010001f578
@property(readonly, nonatomic) _Bool hasPairingID;
@property(nonatomic) _Bool hasVersion;

@end

