//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Sharing/SFActivityAdvertisement.h>

@interface SFActivityAdvertisement (Debug)
- (id)description;	// IMP=0x000000010013f8b8
@end

