//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDNetworkBrowserDelegate-Protocol.h"
#import "SDNetworkOperationDelegate-Protocol.h"

@class NSMutableDictionary, NSMutableSet, NSString, SDActivityAdvertiser, SDActivityEncryptionManager, SDActivityPayloadManager, SDActivityScanner, SDAirDropReceiveManager, SDAutoUnlockSessionManager, SDNearbyIDSAgent, SDPairedDeviceAgent, SDPowerSourceManager, SDUnlockKeyManager, SDUnlockLockManager, SDXPCServer;
@protocol OS_xpc_object;

__attribute__((visibility("hidden")))
@interface SharingDaemon : NSObject <SDNetworkBrowserDelegate, SDNetworkOperationDelegate>
{
    NSMutableSet *_activeObjects;	// 8 = 0x8
    SDActivityAdvertiser *_activityAdvertiser;	// 16 = 0x10
    SDActivityScanner *_activityScanner;	// 24 = 0x18
    SDAirDropReceiveManager *_airdropManager;	// 32 = 0x20
    SDAutoUnlockSessionManager *_autoUnlockSessionManager;	// 40 = 0x28
    SDActivityEncryptionManager *_encryptionManager;	// 48 = 0x30
    SDNearbyIDSAgent *_nearbyIDSAgent;	// 56 = 0x38
    NSMutableDictionary *_exportedOperations;	// 64 = 0x40
    SDPowerSourceManager *_powerSourceManager;	// 72 = 0x48
    SDPairedDeviceAgent *_pairedDeviceAgent;	// 80 = 0x50
    NSObject<OS_xpc_object> *_listener;	// 88 = 0x58
    SDActivityPayloadManager *_payloadManager;	// 96 = 0x60
    SDUnlockKeyManager *_unlockKeyManager;	// 104 = 0x68
    SDUnlockLockManager *_unlockLockManager;	// 112 = 0x70
    unsigned long long _stateHandle;	// 120 = 0x78
    SDXPCServer *_xpcServer;	// 128 = 0x80
}

+ (id)sharedDaemon;	// IMP=0x00000001000c5b60
- (void).cxx_destruct;	// IMP=0x00000001000c8b2c
- (_Bool)canAccessAirDropSettings:(id)arg1;	// IMP=0x00000001000c8b1c
- (void)stop;	// IMP=0x00000001000c89cc
- (void)start;	// IMP=0x00000001000c82c0
- (struct os_state_data_s *)stateCapture;	// IMP=0x00000001000c81b4
@property(readonly, copy) NSString *description;
- (void)handleNewConnection:(id)arg1;	// IMP=0x00000001000c7bf0
- (void)handleOperationMessage:(id)arg1 forConnection:(id)arg2;	// IMP=0x00000001000c7594
- (void)handleBrowserMessage:(id)arg1 forConnection:(id)arg2;	// IMP=0x00000001000c6f90
- (void)networkOperation:(id)arg1 event:(long long)arg2 withResults:(id)arg3;	// IMP=0x00000001000c6990
- (void)networkBrowser:(id)arg1 nodesChangedForParent:(struct __SFNode *)arg2 protocol:(id)arg3 error:(int)arg4;	// IMP=0x00000001000c641c
- (id)xpcArrayForSFNodeArray:(id)arg1;	// IMP=0x00000001000c62d0
- (id)numberFromXPCObject:(id)arg1;	// IMP=0x00000001000c61f4
- (id)arrayFromXPCObject:(id)arg1;	// IMP=0x00000001000c6130
- (id)stringFromXPCObject:(id)arg1;	// IMP=0x00000001000c606c
- (id)xpcObjectForSFOperationResults:(id)arg1;	// IMP=0x00000001000c5ccc
- (void)dealloc;	// IMP=0x00000001000c5c80
- (id)init;	// IMP=0x00000001000c5be0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

