//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString, SDSharePointBrowser;

__attribute__((visibility("hidden")))
@interface TXTQuery : NSObject
{
    NSData *_recordData;	// 8 = 0x8
    struct _DNSServiceRef_t *_service;	// 16 = 0x10
    NSString *_networkProtocol;	// 24 = 0x18
    SDSharePointBrowser *_browser;	// 32 = 0x20
}

@property __weak SDSharePointBrowser *browser; // @synthesize browser=_browser;
@property(retain) NSString *networkProtocol; // @synthesize networkProtocol=_networkProtocol;
@property struct _DNSServiceRef_t *service; // @synthesize service=_service;
@property(retain) NSData *recordData; // @synthesize recordData=_recordData;
- (void).cxx_destruct;	// IMP=0x00000001000b593c

@end

