//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, NSUUID, UIRemoteTextEditingAttributes;

@protocol UIRemoteTextEditing <NSObject>
- (void)endRemoteTextEditingSessionWithID:(NSUUID *)arg1;
- (void)remoteTextEditingSessionWithID:(NSUUID *)arg1 textDidChange:(NSString *)arg2;
- (void)beginRemoteTextEditingSessionWithID:(NSUUID *)arg1 attributes:(UIRemoteTextEditingAttributes *)arg2 initialText:(NSString *)arg3;

@optional
- (void)remoteTextEditingSessionWithID:(NSUUID *)arg1 attributesDidChange:(UIRemoteTextEditingAttributes *)arg2;
@end

