/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:31 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/_LSValidationToken.h>

@interface _LSBundleIDValidationToken : _LSValidationToken
+(BOOL)isToken:(id)arg1 correctForBundleIdentifier:(id)arg2 connection:(id)arg3 ;
+(BOOL)supportsSecureCoding;
-(id)initWithBundleIdentifier:(id)arg1 ;
@end

