/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:32 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSDictionary, NSURL;

@interface _LSOpenConfiguration : NSObject <NSSecureCoding> {

	BOOL _ignoreOpenStrategy;
	NSDictionary* _frontBoardOptions;
	NSURL* _referrerURL;

}

@property (nonatomic,copy) NSDictionary * frontBoardOptions;              //@synthesize frontBoardOptions=_frontBoardOptions - In the implementation block
@property (assign,nonatomic) BOOL ignoreOpenStrategy;                     //@synthesize ignoreOpenStrategy=_ignoreOpenStrategy - In the implementation block
@property (nonatomic,copy) NSURL * referrerURL;                           //@synthesize referrerURL=_referrerURL - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSURL *)referrerURL;
-(void)setReferrerURL:(NSURL *)arg1 ;
-(BOOL)ignoreOpenStrategy;
-(NSDictionary *)frontBoardOptions;
-(void)setFrontBoardOptions:(NSDictionary *)arg1 ;
-(void)setIgnoreOpenStrategy:(BOOL)arg1 ;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
@end

