/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:30 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface _LSQuery : NSObject <NSSecureCoding, NSCopying> {

	BOOL _legacy;

}

@property (assign,getter=isLegacy,nonatomic) BOOL legacy;              //@synthesize legacy=_legacy - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)_canResolveLocallyWithoutMappingDatabase;
-(void)_enumerateWithXPCConnection:(id)arg1 block:(/*^block*/id)arg2 ;
-(BOOL)_shouldCacheResolvedResults;
-(BOOL)_requiresDatabaseMappingEntitlement;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)_init;
-(BOOL)isLegacy;
-(void)setLegacy:(BOOL)arg1 ;
@end

