/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:32 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/_LSQueryResult.h>

@interface _LSQueryResultWithPropertyList : _LSQueryResult {

	id _propertyList;

}

@property (nonatomic,retain,readonly) id propertyList;              //@synthesize propertyList=_propertyList - In the implementation block
+(BOOL)supportsSecureCoding;
-(id)propertyList;
-(id)initWithPropertyList:(id)arg1 ;
-(id)propertyListWithClass:(Class)arg1 ;
-(id)propertyListWithClass:(Class)arg1 valuesOfClass:(Class)arg2 ;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
@end

