/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:32 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/_UTType.h>

@class NSString, NSSet;

@interface _UTConcreteType : _UTType {

	NSString* _identifier;
	NSSet* _pedigree;

}
+(BOOL)supportsSecureCoding;
-(id)parentIdentifiers;
-(BOOL)conformsToType:(id)arg1 ;
-(id)referenceURL;
-(id)_localizedDescriptionWithPreferredLocalizations:(id)arg1 checkingParents:(BOOL)arg2 ;
-(id)declaration;
-(id)declaringBundleURL;
-(BOOL)isDeclared;
-(id)tagSpecification;
-(BOOL)conformsToTypeIdentifier:(id)arg1 ;
-(BOOL)_isPublic;
-(BOOL)_isAppleInternal;
-(id)_unlocalizedDescription;
-(id)_localizedDescriptionDictionary;
-(id)_kernelExtensionName;
-(id)_iconURL;
-(id)initWithIdentifier:(id)arg1 pedigree:(id)arg2 ;
-(id)_pedigree;
-(id)identifier;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(BOOL)_isActive;
-(id)version;
-(BOOL)isDynamic;
@end

