/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:31 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/_LSQueryResult.h>
#import <libobjc.A.dylib/NSSecureCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSDictionary, NSSet, NSURL, NSNumber, NSArray;

@interface _UTType : _LSQueryResult <NSSecureCoding, NSCopying>

@property (getter=_isWildcard,nonatomic,readonly) BOOL _wildcard; 
@property (getter=_isActive,nonatomic,readonly) BOOL _active; 
@property (getter=_isPublic,nonatomic,readonly) BOOL _public; 
@property (getter=_isAppleInternal,nonatomic,readonly) BOOL _appleInternal; 
@property (nonatomic,readonly) NSString * _unlocalizedDescription; 
@property (nonatomic,readonly) NSDictionary * _localizedDescriptionDictionary; 
@property (nonatomic,readonly) NSString * _kernelExtensionName; 
@property (nonatomic,readonly) NSSet * _pedigree; 
@property (nonatomic,readonly) NSURL * _iconURL; 
@property (nonatomic,readonly) NSString * identifier; 
@property (nonatomic,readonly) NSNumber * version; 
@property (nonatomic,readonly) NSString * localizedDescription; 
@property (nonatomic,readonly) NSURL * declaringBundleURL; 
@property (nonatomic,readonly) NSDictionary * declaration; 
@property (getter=isDynamic,nonatomic,readonly) BOOL dynamic; 
@property (getter=isDeclared,nonatomic,readonly) BOOL declared; 
@property (nonatomic,readonly) NSDictionary * tagSpecification; 
@property (nonatomic,readonly) NSURL * referenceURL; 
@property (nonatomic,readonly) NSArray * parentIdentifiers; 
+(BOOL)_isDeclaration:(id)arg1 equalToDeclaration:(id)arg2 ;
+(id)_localizationDictionaryForTypeWithIdentifier:(id)arg1 unit:(unsigned)arg2 preferredLocalizations:(id)arg3 ;
+(CFArrayRef)_copyIdentifiersWithQuery:(id)arg1 ;
-(NSArray *)parentIdentifiers;
-(BOOL)conformsToType:(id)arg1 ;
-(NSURL *)referenceURL;
-(id)_localizedDescriptionWithPreferredLocalizations:(id)arg1 checkingParents:(BOOL)arg2 ;
-(NSDictionary *)declaration;
-(NSURL *)declaringBundleURL;
-(BOOL)isDeclared;
-(NSDictionary *)tagSpecification;
-(BOOL)conformsToTypeIdentifier:(id)arg1 ;
-(BOOL)_isPublic;
-(BOOL)_isAppleInternal;
-(NSString *)_unlocalizedDescription;
-(NSDictionary *)_localizedDescriptionDictionary;
-(NSString *)_kernelExtensionName;
-(NSURL *)_iconURL;
-(void)_enumerateParentTypesWithBlock:(/*^block*/id)arg1 ;
-(BOOL)_isWildcard;
-(NSSet *)_pedigree;
-(NSString *)identifier;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)debugDescription;
-(BOOL)_isActive;
-(NSNumber *)version;
-(NSString *)localizedDescription;
-(BOOL)isDynamic;
@end

