/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:31 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/LSBundleProxy.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSArray, NSNumber, NSDate, _LSDiskUsage, _LSApplicationState, NSUUID, NSProgress, NSDictionary;

@interface LSApplicationProxy : LSBundleProxy <NSSecureCoding> {

	NSString* _deviceIdentifierVendorName;
	NSArray* _pluginUUIDs;
	NSNumber* _versionID;
	BOOL _userInitiatedUninstall;
	int _bundleModTime;
	NSArray* _plugInKitPlugins;
	NSString* _signerOrganization;
	NSString* _companionApplicationIdentifier;
	NSArray* _counterpartIdentifiers;
	NSDate* _registeredDate;
	NSNumber* _itemID;
	NSString* _vendorName;
	NSString* _itemName;
	NSString* _genre;
	NSNumber* _genreID;
	NSString* _minimumSystemVersion;
	NSString* _maximumSystemVersion;
	NSString* _shortVersionString;
	NSString* _preferredArchitecture;
	_LSDiskUsage* _diskUsage;
	_LSApplicationState* _appState;
	NSNumber* _purchaserDSID;
	NSNumber* _downloaderDSID;
	NSNumber* _familyID;
	unsigned long long _installType;
	unsigned long long _originalInstallType;
	NSArray* _deviceFamily;
	NSArray* _activityTypes;
	NSString* _teamID;
	NSNumber* _storeFront;
	NSNumber* _ratingRank;
	NSString* _ratingLabel;
	NSString* _sourceAppIdentifier;
	NSString* _applicationVariant;
	NSString* _watchKitVersion;
	NSString* _complicationPrincipalClass;
	NSArray* _supportedComplicationFamilies;
	NSNumber* _installFailureReason;
	NSString* _appStoreToolsBuildVersion;

}

@property (nonatomic,readonly) double installPercentage; 
@property (nonatomic,readonly) long long installProgressState; 
@property (getter=isInstallPaused,nonatomic,readonly) BOOL installPaused; 
@property (nonatomic,readonly) BOOL pbs_enabled; 
@property (nonatomic,readonly) BOOL tvs_isLegacyApp; 
@property (readonly) NSArray * _inf_userActivityTypes; 
@property (assign,nonatomic) BOOL userInitiatedUninstall;                                          //@synthesize userInitiatedUninstall=_userInitiatedUninstall - In the implementation block
@property (nonatomic,readonly) BOOL supportsAlternateIconNames; 
@property (nonatomic,readonly) int bundleModTime;                                                  //@synthesize bundleModTime=_bundleModTime - In the implementation block
@property (nonatomic,readonly) NSString * applicationIdentifier; 
@property (nonatomic,readonly) NSString * companionApplicationIdentifier;                          //@synthesize companionApplicationIdentifier=_companionApplicationIdentifier - In the implementation block
@property (nonatomic,readonly) NSArray * counterpartIdentifiers;                                   //@synthesize counterpartIdentifiers=_counterpartIdentifiers - In the implementation block
@property (nonatomic,readonly) NSDate * registeredDate;                                            //@synthesize registeredDate=_registeredDate - In the implementation block
@property (nonatomic,readonly) NSNumber * itemID;                                                  //@synthesize itemID=_itemID - In the implementation block
@property (nonatomic,readonly) NSString * vendorName;                                              //@synthesize vendorName=_vendorName - In the implementation block
@property (nonatomic,readonly) NSString * itemName;                                                //@synthesize itemName=_itemName - In the implementation block
@property (nonatomic,readonly) NSString * storeCohortMetadata; 
@property (nonatomic,readonly) NSString * genre;                                                   //@synthesize genre=_genre - In the implementation block
@property (nonatomic,readonly) NSNumber * genreID;                                                 //@synthesize genreID=_genreID - In the implementation block
@property (nonatomic,readonly) NSArray * subgenres; 
@property (nonatomic,readonly) NSArray * staticShortcutItems; 
@property (nonatomic,readonly) NSString * minimumSystemVersion;                                    //@synthesize minimumSystemVersion=_minimumSystemVersion - In the implementation block
@property (nonatomic,readonly) NSString * maximumSystemVersion;                                    //@synthesize maximumSystemVersion=_maximumSystemVersion - In the implementation block
@property (nonatomic,readonly) NSString * shortVersionString;                                      //@synthesize shortVersionString=_shortVersionString - In the implementation block
@property (nonatomic,readonly) NSString * preferredArchitecture;                                   //@synthesize preferredArchitecture=_preferredArchitecture - In the implementation block
@property (nonatomic,readonly) NSString * applicationType; 
@property (nonatomic,readonly) NSArray * directionsModes; 
@property (nonatomic,readonly) NSArray * UIBackgroundModes; 
@property (nonatomic,readonly) NSArray * audioComponents; 
@property (nonatomic,readonly) NSUUID * deviceIdentifierForVendor; 
@property (nonatomic,readonly) NSUUID * deviceIdentifierForAdvertising; 
@property (nonatomic,readonly) NSProgress * installProgress; 
@property (nonatomic,readonly) NSNumber * staticDiskUsage; 
@property (nonatomic,readonly) NSNumber * dynamicDiskUsage; 
@property (nonatomic,readonly) NSNumber * ODRDiskUsage; 
@property (nonatomic,readonly) _LSDiskUsage * diskUsage;                                           //@synthesize diskUsage=_diskUsage - In the implementation block
@property (nonatomic,readonly) _LSApplicationState * appState;                                     //@synthesize appState=_appState - In the implementation block
@property (getter=isInstalled,nonatomic,readonly) BOOL installed; 
@property (getter=isPlaceholder,nonatomic,readonly) BOOL placeholder; 
@property (getter=isRestricted,nonatomic,readonly) BOOL restricted; 
@property (getter=isRemovedSystemApp,nonatomic,readonly) BOOL removedSystemApp; 
@property (nonatomic,readonly) NSArray * VPNPlugins; 
@property (nonatomic,readonly) NSArray * plugInKitPlugins;                                         //@synthesize plugInKitPlugins=_plugInKitPlugins - In the implementation block
@property (nonatomic,readonly) NSArray * appTags; 
@property (nonatomic,readonly) NSString * applicationDSID; 
@property (nonatomic,readonly) NSNumber * purchaserDSID;                                           //@synthesize purchaserDSID=_purchaserDSID - In the implementation block
@property (nonatomic,readonly) NSNumber * downloaderDSID;                                          //@synthesize downloaderDSID=_downloaderDSID - In the implementation block
@property (nonatomic,readonly) NSNumber * familyID;                                                //@synthesize familyID=_familyID - In the implementation block
@property (nonatomic,readonly) unsigned long long installType;                                     //@synthesize installType=_installType - In the implementation block
@property (nonatomic,readonly) unsigned long long originalInstallType;                             //@synthesize originalInstallType=_originalInstallType - In the implementation block
@property (nonatomic,readonly) NSArray * requiredDeviceCapabilities; 
@property (nonatomic,readonly) NSArray * deviceFamily;                                             //@synthesize deviceFamily=_deviceFamily - In the implementation block
@property (nonatomic,readonly) NSArray * activityTypes;                                            //@synthesize activityTypes=_activityTypes - In the implementation block
@property (nonatomic,readonly) NSArray * externalAccessoryProtocols; 
@property (nonatomic,readonly) NSString * teamID;                                                  //@synthesize teamID=_teamID - In the implementation block
@property (nonatomic,readonly) NSNumber * storeFront;                                              //@synthesize storeFront=_storeFront - In the implementation block
@property (nonatomic,readonly) NSNumber * externalVersionIdentifier; 
@property (nonatomic,readonly) NSNumber * betaExternalVersionIdentifier; 
@property (nonatomic,readonly) NSNumber * ratingRank;                                              //@synthesize ratingRank=_ratingRank - In the implementation block
@property (nonatomic,readonly) NSString * ratingLabel;                                             //@synthesize ratingLabel=_ratingLabel - In the implementation block
@property (nonatomic,readonly) NSString * sourceAppIdentifier;                                     //@synthesize sourceAppIdentifier=_sourceAppIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * applicationVariant;                                      //@synthesize applicationVariant=_applicationVariant - In the implementation block
@property (getter=isAppUpdate,nonatomic,readonly) BOOL appUpdate; 
@property (nonatomic,readonly) BOOL hasParallelPlaceholder; 
@property (getter=isNewsstandApp,nonatomic,readonly) BOOL newsstandApp; 
@property (getter=isWhitelisted,nonatomic,readonly) BOOL whitelisted; 
@property (getter=isAppStoreVendable,nonatomic,readonly) BOOL appStoreVendable; 
@property (getter=isDeviceBasedVPP,nonatomic,readonly) BOOL deviceBasedVPP; 
@property (getter=isBetaApp,nonatomic,readonly) BOOL betaApp; 
@property (getter=isAdHocCodeSigned,nonatomic,readonly) BOOL adHocCodeSigned; 
@property (nonatomic,readonly) BOOL supportsAudiobooks; 
@property (getter=isLaunchProhibited,nonatomic,readonly) BOOL launchProhibited; 
@property (nonatomic,readonly) BOOL supportsODR; 
@property (nonatomic,readonly) BOOL hasSettingsBundle; 
@property (nonatomic,readonly) BOOL supportsExternallyPlayableContent; 
@property (nonatomic,readonly) BOOL supportsOpenInPlace; 
@property (nonatomic,readonly) BOOL fileSharingEnabled; 
@property (nonatomic,readonly) BOOL iconIsPrerendered; 
@property (nonatomic,readonly) BOOL iconUsesAssetCatalog; 
@property (getter=isPurchasedReDownload,nonatomic,readonly) BOOL purchasedReDownload; 
@property (nonatomic,readonly) BOOL hasMIDBasedSINF; 
@property (nonatomic,readonly) BOOL missingRequiredSINF; 
@property (nonatomic,readonly) BOOL supportsPurgeableLocalStorage; 
@property (getter=isDeletable,nonatomic,readonly) BOOL deletable; 
@property (getter=isRemoveableSystemApp,nonatomic,readonly) BOOL removeableSystemApp; 
@property (getter=isWatchKitApp,nonatomic,readonly) BOOL watchKitApp; 
@property (nonatomic,readonly) NSString * watchKitVersion;                                         //@synthesize watchKitVersion=_watchKitVersion - In the implementation block
@property (readonly) NSString * complicationPrincipalClass;                                        //@synthesize complicationPrincipalClass=_complicationPrincipalClass - In the implementation block
@property (readonly) NSArray * supportedComplicationFamilies;                                      //@synthesize supportedComplicationFamilies=_supportedComplicationFamilies - In the implementation block
@property (nonatomic,readonly) BOOL hasCustomNotification; 
@property (readonly) BOOL hasComplication; 
@property (nonatomic,readonly) BOOL hasGlance; 
@property (nonatomic,readonly) BOOL shouldSkipWatchAppInstall; 
@property (getter=isGameCenterEnabled,nonatomic,readonly) BOOL gameCenterEnabled; 
@property (nonatomic,readonly) BOOL gameCenterEverEnabled; 
@property (nonatomic,readonly) NSNumber * installFailureReason;                                    //@synthesize installFailureReason=_installFailureReason - In the implementation block
@property (nonatomic,readonly) long long deviceManagementPolicy; 
@property (nonatomic,readonly) NSDictionary * siriActionDefinitionURLs; 
@property (nonatomic,readonly) NSString * appStoreToolsBuildVersion;                               //@synthesize appStoreToolsBuildVersion=_appStoreToolsBuildVersion - In the implementation block
+(id)_tv_placeholderIconImage;
+(id)tv_placeholderLayeredIcon;
+(void)tv_initializeFlatIconCache;
+(void)tv_disableLSWorkspaceInstallHandling;
+(id)_tvsui_placeholderLayeredIconAtSystemScale;
+(id)_tvsui_placeholderIconImage;
+(id)tvsui_placeholderLayeredIcon;
+(void)tvsui_initializeFlatIconCache;
+(void)tvsui_disableLSWorkspaceInstallHandling;
+(id)applicationProxyForCompanionIdentifier:(id)arg1 ;
+(id)applicationProxyForBundleURL:(id)arg1 ;
+(id)applicationProxyForIdentifier:(id)arg1 placeholder:(BOOL)arg2 ;
+(id)applicationProxyForSystemPlaceholder:(id)arg1 ;
+(id)applicationProxyWithBundleUnitID:(unsigned)arg1 withContext:(LSContext*)arg2 ;
+(id)applicationProxyForIdentifier:(id)arg1 withContext:(LSContext*)arg2 ;
+(id)applicationProxyForBundleType:(unsigned long long)arg1 identifier:(id)arg2 isCompanion:(BOOL)arg3 URL:(id)arg4 itemID:(id)arg5 bundleUnit:(unsigned*)arg6 ;
+(id)iconQueue;
+(id)applicationProxyForItemID:(id)arg1 ;
+(BOOL)supportsSecureCoding;
+(id)applicationProxyForIdentifier:(id)arg1 ;
-(BOOL)isMISAuthorized;
-(id)tv_applicationFlatIcon;
-(id)tv_supportedUserInterfaceStyles;
-(id)_tv_applicationIconName;
-(id)_tv_uncachedAssetManager;
-(id)_tv_cachedFlatApplicationIcon;
-(id)_tv_cachedSmallFlatApplicationIcon;
-(id)_tv_assetManager;
-(double)installPercentage;
-(id)tv_displayNameForAppState:(id)arg1 withLocalizedAppName:(id)arg2 ;
-(BOOL)isInstallPaused;
-(long long)installProgressState;
-(void)tv_preheatApplicationIcon;
-(void)tv_preheatSmallApplicationIcon;
-(void)tv_preheatApplicationName;
-(void)tv_flushApplicationCachedImages;
-(id)tv_smallApplicationFlatIcon;
-(id)tv_volatileApplicationLayeredIcon;
-(id)tv_volatileTopShelfImage;
-(id)tv_applicationLaunchImageName;
-(BOOL)tv_applicationLaunchImageIsTemplate;
-(long long)tv_preferredUserInterfaceStyle;
-(id)tv_displayNameForAppState:(id)arg1 ;
-(id)tv_cacheKey;
-(double)tv_lastModifiedDate;
-(id)tv_bundlePathHash;
-(id)tv_iconCacheKey;
-(id)_tvsui_applicationIconName;
-(id)_tvsui_uncachedAssetManager;
-(id)_tvsui_cachedFlatApplicationIcon;
-(id)_tvsui_cachedSmallFlatApplicationIcon;
-(id)_tvsui_assetManager;
-(id)tvsui_supportedUserInterfaceStyles;
-(BOOL)_isNotInstalled;
-(BOOL)_tvsui_isSoftFailure;
-(double)tvsui_installPercentage;
-(id)tvsui_displayNameForAppState:(id)arg1 withLocalizedAppName:(id)arg2 ;
-(BOOL)tvsui_isInstallPaused;
-(long long)tvsui_installProgressState;
-(void)tvsui_preheatApplicationIcon;
-(void)tvsui_preheatSmallApplicationIcon;
-(void)tvsui_preheatApplicationName;
-(void)tvsui_flushApplicationCachedImages;
-(id)tvsui_smallApplicationFlatIcon;
-(id)tvsui_volatileApplicationLayeredIcon;
-(id)tvsui_volatileTopShelfImage;
-(id)tvsui_applicationLaunchImageName;
-(BOOL)tvsui_applicationLaunchImageIsTemplate;
-(long long)tvsui_preferredUserInterfaceStyle;
-(id)tvsui_displayNameForAppState:(id)arg1 ;
-(id)tvsui_applicationFlatIcon;
-(id)tvsui_cacheKey;
-(double)tvsui_lastModifiedDate;
-(id)tvsui_bundlePathHash;
-(id)tvsui_iconCacheKey;
-(BOOL)_pbs_disabledViaInfoPlist;
-(BOOL)_pbs_appPreferencesAllowVisibility;
-(BOOL)pbs_enabled;
-(id)pbsAppTags;
-(id)tvs_bundle;
-(BOOL)tvs_isLegacyApp;
-(CGSize)_defaultStyleSize:(id)arg1 ;
-(SCD_Struct_LS7*)_iconVariantDefinitions:(id)arg1 ;
-(id)un_applicationBundleURL;
-(id)un_applicationBundleIdentifier;
-(BOOL)_inapptrust_isFirstParty;
-(NSArray *)_inf_userActivityTypes;
-(NSString *)sourceAppIdentifier;
-(NSArray *)plugInKitPlugins;
-(NSArray *)counterpartIdentifiers;
-(NSNumber *)betaExternalVersionIdentifier;
-(BOOL)isDeviceBasedVPP;
-(NSArray *)requiredDeviceCapabilities;
-(BOOL)isGameCenterEnabled;
-(unsigned long long)installType;
-(NSNumber *)externalVersionIdentifier;
-(NSNumber *)purchaserDSID;
-(BOOL)profileValidated;
-(BOOL)isLaunchProhibited;
-(NSArray *)appTags;
-(BOOL)isDeletable;
-(BOOL)hasSettingsBundle;
-(BOOL)isAppStoreVendable;
-(NSDate *)registeredDate;
-(NSNumber *)ratingRank;
-(NSNumber *)genreID;
-(NSString *)genre;
-(NSNumber *)itemID;
-(NSString *)ratingLabel;
-(NSString *)vendorName;
-(NSString *)itemName;
-(NSString *)teamID;
-(BOOL)isBetaApp;
-(BOOL)isNewsstandApp;
-(NSArray *)deviceFamily;
-(long long)deviceManagementPolicy;
-(NSArray *)subgenres;
-(NSArray *)externalAccessoryProtocols;
-(id)localizedNameForContext:(id)arg1 preferredLocalizations:(id)arg2 ;
-(id)resourcesDirectoryURL;
-(BOOL)isWatchKitApp;
-(NSString *)companionApplicationIdentifier;
-(NSArray *)UIBackgroundModes;
-(BOOL)isWhitelisted;
-(void)clearAdvertisingIdentifier;
-(NSUUID *)deviceIdentifierForAdvertising;
-(int)bundleModTime;
-(id)_initWithBundleUnit:(unsigned)arg1 context:(LSContext*)arg2 applicationIdentifier:(id)arg3 ;
-(_LSDiskUsage *)diskUsage;
-(id)iconDataForVariant:(int)arg1 preferredIconName:(id)arg2 withOptions:(int)arg3 ;
-(NSArray *)supportedComplicationFamilies;
-(NSString *)complicationPrincipalClass;
-(NSString *)storeCohortMetadata;
-(NSArray *)staticShortcutItems;
-(NSString *)applicationDSID;
-(NSArray *)directionsModes;
-(NSArray *)audioComponents;
-(NSNumber *)staticDiskUsage;
-(NSNumber *)dynamicDiskUsage;
-(NSNumber *)ODRDiskUsage;
-(NSArray *)VPNPlugins;
-(id)getBundleMetadata;
-(id)installProgressSync;
-(id)primaryIconDataForVariant:(int)arg1 ;
-(BOOL)supportsAlternateIconNames;
-(BOOL)iconUsesAssetCatalog;
-(BOOL)fileSharingEnabled;
-(BOOL)UPPValidated;
-(BOOL)hasParallelPlaceholder;
-(BOOL)supportsAudiobooks;
-(BOOL)supportsODR;
-(BOOL)supportsExternallyPlayableContent;
-(BOOL)isPurchasedReDownload;
-(BOOL)hasCustomNotification;
-(BOOL)hasComplication;
-(BOOL)hasGlance;
-(BOOL)shouldSkipWatchAppInstall;
-(BOOL)missingRequiredSINF;
-(BOOL)supportsPurgeableLocalStorage;
-(BOOL)gameCenterEverEnabled;
-(BOOL)isRemoveableSystemApp;
-(BOOL)isRemovedSystemApp;
-(void)getDeviceManagementPolicyWithCompletionHandler:(/*^block*/id)arg1 ;
-(NSDictionary *)siriActionDefinitionURLs;
-(id)signerOrganization;
-(NSString *)minimumSystemVersion;
-(NSString *)maximumSystemVersion;
-(NSString *)preferredArchitecture;
-(NSNumber *)familyID;
-(unsigned long long)originalInstallType;
-(NSArray *)activityTypes;
-(NSNumber *)storeFront;
-(NSString *)applicationVariant;
-(NSString *)watchKitVersion;
-(NSNumber *)installFailureReason;
-(NSString *)appStoreToolsBuildVersion;
-(BOOL)userInitiatedUninstall;
-(void)setUserInitiatedUninstall:(BOOL)arg1 ;
-(id)localizedNameForContext:(id)arg1 preferredLocalizations:(id)arg2 useShortNameOnly:(BOOL)arg3 ;
-(id)localizedNameWithPreferredLocalizations:(id)arg1 useShortNameOnly:(BOOL)arg2 ;
-(BOOL)isAdHocCodeSigned;
-(BOOL)hasMIDBasedSINF;
-(BOOL)isAppUpdate;
-(NSNumber *)downloaderDSID;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(id)iconDataForVariant:(int)arg1 ;
-(BOOL)isPlaceholder;
-(id)alternateIconName;
-(id)iconDataForVariant:(int)arg1 withOptions:(int)arg2 ;
-(NSUUID *)deviceIdentifierForVendor;
-(BOOL)isRestricted;
-(void)setAlternateIconName:(id)arg1 withResult:(/*^block*/id)arg2 ;
-(id)localizedNameForContext:(id)arg1 ;
-(NSString *)applicationType;
-(NSString *)applicationIdentifier;
-(_LSApplicationState *)appState;
-(BOOL)isInstalled;
-(BOOL)supportsOpenInPlace;
-(id)uniqueIdentifier;
-(BOOL)iconIsPrerendered;
-(NSString *)shortVersionString;
-(NSProgress *)installProgress;
@end

