/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:32 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/_LSQueryResult.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSDictionary;

@interface LSExtensionPoint : _LSQueryResult <NSCopying, NSSecureCoding> {

	NSString* _identifier;
	NSString* _name;
	NSString* _version;
	NSDictionary* _sdkEntry;

}

@property (nonatomic,readonly) NSString * identifier;                //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) NSString * name;                      //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSString * version;                   //@synthesize version=_version - In the implementation block
@property (nonatomic,readonly) NSDictionary * sdkEntry;              //@synthesize sdkEntry=_sdkEntry - In the implementation block
+(id)extensionPointForIdentifier:(id)arg1 ;
+(id)identifierForCurrentProcess;
+(BOOL)supportsSecureCoding;
-(NSDictionary *)sdkEntry;
-(id)_initWithIdentifier:(id)arg1 andData:(id)arg2 ;
-(void)dealloc;
-(NSString *)identifier;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)name;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)version;
@end

