/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:31 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/LSBundleProxy.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSUUID, NSDate, LSBundleProxy, NSDictionary;

@interface LSPlugInKitProxy : LSBundleProxy <NSSecureCoding> {

	BOOL _onSystemPartition;
	NSString* _signerOrganization;
	NSString* _pluginIdentifier;
	NSString* _originalIdentifier;
	NSString* _protocol;
	NSUUID* _pluginUUID;
	NSDate* _registrationDate;
	LSBundleProxy* _containingBundle;

}

@property (nonatomic,readonly) NSString * pluginIdentifier;                                    //@synthesize pluginIdentifier=_pluginIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * originalIdentifier;                                  //@synthesize originalIdentifier=_originalIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * protocol;                                            //@synthesize protocol=_protocol - In the implementation block
@property (nonatomic,readonly) NSUUID * pluginUUID;                                            //@synthesize pluginUUID=_pluginUUID - In the implementation block
@property (nonatomic,readonly) NSDictionary * pluginKitDictionary; 
@property (nonatomic,readonly) NSDictionary * infoPlist; 
@property (nonatomic,readonly) NSDate * registrationDate;                                      //@synthesize registrationDate=_registrationDate - In the implementation block
@property (nonatomic,readonly) LSBundleProxy * containingBundle;                               //@synthesize containingBundle=_containingBundle - In the implementation block
@property (getter=isOnSystemPartition,nonatomic,readonly) BOOL onSystemPartition;              //@synthesize onSystemPartition=_onSystemPartition - In the implementation block
@property (nonatomic,readonly) NSString * teamID; 
+(id)pluginKitProxyForURL:(id)arg1 ;
+(id)pluginKitProxyForIdentifier:(id)arg1 ;
+(id)plugInKitProxyForUUID:(id)arg1 bundleIdentifier:(id)arg2 pluginIdentifier:(id)arg3 effectiveIdentifier:(id)arg4 version:(id)arg5 bundleURL:(id)arg6 ;
+(id)containingBundleIdentifiersForPlugInBundleIdentifiers:(id)arg1 error:(id*)arg2 ;
+(id)plugInKitProxyForPlugin:(unsigned)arg1 withContext:(LSContext*)arg2 ;
+(BOOL)supportsSecureCoding;
+(id)pluginKitProxyForUUID:(id)arg1 ;
-(id)un_applicationBundleURL;
-(id)un_applicationBundleIdentifier;
-(NSDictionary *)pluginKitDictionary;
-(BOOL)profileValidated;
-(NSDate *)registrationDate;
-(NSString *)teamID;
-(id)objectForInfoDictionaryKey:(id)arg1 ofClass:(Class)arg2 inScope:(unsigned long long)arg3 ;
-(NSString *)pluginIdentifier;
-(BOOL)UPPValidated;
-(id)signerOrganization;
-(id)localizedNameWithPreferredLocalizations:(id)arg1 useShortNameOnly:(BOOL)arg2 ;
-(id)_initWithPlugin:(unsigned)arg1 andContext:(LSContext*)arg2 ;
-(NSString *)originalIdentifier;
-(id)_initWithUUID:(id)arg1 bundleIdentifier:(id)arg2 pluginIdentifier:(id)arg3 effectiveIdentifier:(id)arg4 version:(id)arg5 bundleURL:(id)arg6 ;
-(NSUUID *)pluginUUID;
-(BOOL)pluginCanProvideIcon;
-(id)boundIconsDictionary;
-(BOOL)isOnSystemPartition;
-(id)_valueForEqualityTesting;
-(NSDictionary *)infoPlist;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(LSBundleProxy *)containingBundle;
-(id)iconDataForVariant:(int)arg1 withOptions:(int)arg2 ;
-(NSString *)protocol;
@end

