/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:31 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreServices/CoreServices-Structs.h>
#import <CoreServices/_LSQuery.h>

@interface LSPlugInQuery : _LSQuery
+(id)pluginQuery;
+(id)pluginQueryWithQueryDictionary:(id)arg1 applyFilter:(/*^block*/id)arg2 ;
+(id)pluginQueryWithUUID:(id)arg1 ;
+(id)pluginQueryWithIdentifier:(id)arg1 ;
+(id)pluginQueryWithURL:(id)arg1 ;
+(BOOL)supportsSecureCoding;
-(void)sort:(BOOL)arg1 pluginIDs:(id)arg2 andYield:(/*^block*/id)arg3 context:(LSContext*)arg4 ;
-(void)_enumerateWithXPCConnection:(id)arg1 block:(/*^block*/id)arg2 ;
-(BOOL)_shouldCacheResolvedResults;
-(BOOL)_requiresDatabaseMappingEntitlement;
-(BOOL)isEqual:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(unsigned long long)hash;
@end

