/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:02 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFAirDropActivityViewControllerDelegate <NSObject>
@optional
-(void)airDropActivityDoneButtonPressed;
-(void)airDropActivityRequestingSharedItemsWithOptions:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)airDropActivityDidFailToStartTransfer;

@required
-(void)airDropActivityRequestingSharedItemsWithCompletionHandler:(/*^block*/id)arg1;
-(void)airDropActivityDidSuccessfullyCompleteTransfer;
-(void)airDropActivityDidSuccessfullyStartTransfer;

@end

