/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:02 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Sharing/SFPeerDevice.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSUUID, NSDictionary, NSData;

@interface SFAutoUnlockDevice : SFPeerDevice <NSSecureCoding> {

	BOOL _unlockEnabled;
	BOOL _keyExists;
	BOOL _bluetoothCloudPaired;
	BOOL _placeholder;
	BOOL _supportsAlwaysDirect;
	BOOL _supportsAuthPrompts;
	BOOL _supportsEncryption;
	BOOL _supportsAdvertisingUnlocked;
	BOOL _supportsConnectionCache;
	NSString* _modelDescription;
	NSUUID* _bluetoothID;
	NSUUID* _proxyBluetoothID;
	NSString* _modelName;
	NSDictionary* _results;
	NSData* _hintToken;
	long long _majorOSVersion;

}

@property (nonatomic,copy) NSString * modelDescription;                     //@synthesize modelDescription=_modelDescription - In the implementation block
@property (assign,nonatomic) BOOL unlockEnabled;                            //@synthesize unlockEnabled=_unlockEnabled - In the implementation block
@property (assign,nonatomic) BOOL bluetoothCloudPaired;                     //@synthesize bluetoothCloudPaired=_bluetoothCloudPaired - In the implementation block
@property (nonatomic,retain) NSUUID * bluetoothID;                          //@synthesize bluetoothID=_bluetoothID - In the implementation block
@property (nonatomic,copy) NSUUID * proxyBluetoothID;                       //@synthesize proxyBluetoothID=_proxyBluetoothID - In the implementation block
@property (nonatomic,readonly) long long type; 
@property (nonatomic,retain) NSString * modelName;                          //@synthesize modelName=_modelName - In the implementation block
@property (nonatomic,retain) NSDictionary * results;                        //@synthesize results=_results - In the implementation block
@property (nonatomic,retain) NSData * hintToken;                            //@synthesize hintToken=_hintToken - In the implementation block
@property (assign,nonatomic) BOOL placeholder;                              //@synthesize placeholder=_placeholder - In the implementation block
@property (assign,nonatomic) BOOL supportsAlwaysDirect;                     //@synthesize supportsAlwaysDirect=_supportsAlwaysDirect - In the implementation block
@property (assign,nonatomic) BOOL supportsAuthPrompts;                      //@synthesize supportsAuthPrompts=_supportsAuthPrompts - In the implementation block
@property (assign,nonatomic) BOOL supportsEncryption;                       //@synthesize supportsEncryption=_supportsEncryption - In the implementation block
@property (assign,nonatomic) BOOL supportsAdvertisingUnlocked;              //@synthesize supportsAdvertisingUnlocked=_supportsAdvertisingUnlocked - In the implementation block
@property (assign,nonatomic) BOOL supportsConnectionCache;                  //@synthesize supportsConnectionCache=_supportsConnectionCache - In the implementation block
@property (assign,nonatomic) long long majorOSVersion;                      //@synthesize majorOSVersion=_majorOSVersion - In the implementation block
@property (assign,nonatomic) BOOL keyExists;                                //@synthesize keyExists=_keyExists - In the implementation block
+(BOOL)supportsSecureCoding;
-(BOOL)bluetoothCloudPaired;
-(NSUUID *)bluetoothID;
-(BOOL)unlockEnabled;
-(NSString *)modelDescription;
-(void)setModelDescription:(NSString *)arg1 ;
-(void)setUnlockEnabled:(BOOL)arg1 ;
-(BOOL)keyExists;
-(void)setKeyExists:(BOOL)arg1 ;
-(void)setBluetoothCloudPaired:(BOOL)arg1 ;
-(void)setBluetoothID:(NSUUID *)arg1 ;
-(NSUUID *)proxyBluetoothID;
-(void)setProxyBluetoothID:(NSUUID *)arg1 ;
-(void)setModelName:(NSString *)arg1 ;
-(NSData *)hintToken;
-(void)setHintToken:(NSData *)arg1 ;
-(BOOL)supportsAlwaysDirect;
-(void)setSupportsAlwaysDirect:(BOOL)arg1 ;
-(BOOL)supportsAuthPrompts;
-(void)setSupportsAuthPrompts:(BOOL)arg1 ;
-(BOOL)supportsEncryption;
-(void)setSupportsEncryption:(BOOL)arg1 ;
-(BOOL)supportsAdvertisingUnlocked;
-(void)setSupportsAdvertisingUnlocked:(BOOL)arg1 ;
-(BOOL)supportsConnectionCache;
-(void)setSupportsConnectionCache:(BOOL)arg1 ;
-(long long)majorOSVersion;
-(void)setMajorOSVersion:(long long)arg1 ;
-(NSString *)modelName;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(void)setPlaceholder:(BOOL)arg1 ;
-(long long)type;
-(BOOL)placeholder;
-(NSDictionary *)results;
-(void)setResults:(NSDictionary *)arg1 ;
@end

