/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:03 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFContinuityScannerClient <NSObject>
@required
-(void)lostDeviceWithDevice:(id)arg1;
-(void)receivedAdvertisement:(id)arg1;
-(void)foundDeviceWithDevice:(id)arg1;
-(void)pairedDevicesChanged:(id)arg1;

@end

