/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:03 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFCompanionServiceManagerClient <NSObject>
@required
-(void)streamToService:(id)arg1 withFileHandle:(id)arg2 acceptReply:(/*^block*/id)arg3;

@end

