/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:03 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFContinuityScanManagerObserver <NSObject>
@required
-(void)scanManager:(id)arg1 receivedAdvertisement:(id)arg2;
-(void)scanManager:(id)arg1 foundDeviceWithDevice:(id)arg2;
-(void)scanManager:(id)arg1 lostDeviceWithDevice:(id)arg2;
-(void)scanManager:(id)arg1 pairedDevicesChanged:(id)arg2;

@end

