/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:04 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSString, SFSession, SFDeviceOperationCDPSetup, SFDeviceOperationHomeKitSetup, TRSession, NSMutableArray, TROperationQueue, NSSet, NSObject, SFDevice, UIViewController;

@interface SFDeviceSetupAppleTVSession : NSObject {

	BOOL _activateCalled;
	int _finishState;
	BOOL _invalidateCalled;
	int _proxSetupActiveToken;
	BOOL _useSFSession;
	int _preflightWiFiState;
	int _preflightiTunesState;
	NSString* _iTunesUserID;
	SFSession* _sfSession;
	int _sfSessionState;
	int _preAuthState;
	int _basicConfigState;
	BOOL _iCloudAccountMatches;
	int _pairSetupState;
	double _pairSetupSecs;
	BOOL _cdpEnabled;
	SFDeviceOperationCDPSetup* _cdpSetupOperation;
	double _cdpSetupSecs;
	int _cdpState;
	BOOL _homeKitDoKeyExchange;
	BOOL _homeKitDoFullSetup;
	SFDeviceOperationHomeKitSetup* _homeKitSetupOperation;
	int _homeKitUserInputState;
	int _homeKitSetupState;
	double _homeKitSetupSecs;
	NSString* _homeKitSelectedRoomName;
	int _trSessionState;
	TRSession* _trSession;
	NSMutableArray* _trOperations;
	TROperationQueue* _trOperationQueue;
	int _trSetupConfigurationState;
	unsigned long long _trSetupConfigurationStartTicks;
	double _trSetupConfigurationSecs;
	BOOL _trNeedsNetwork;
	NSSet* _trUnauthServices;
	int _trNetworkState;
	unsigned long long _trNetworkStartTicks;
	double _wifiSetupSecs;
	int _trActivationState;
	unsigned long long _trActivationStartTicks;
	double _trActivationSecs;
	int _trAuthenticationState;
	unsigned long long _trAuthenticationStartTicks;
	double _trAuthenticationSecs;
	int _trCompletionState;
	unsigned long long _trCompletionStartTicks;
	double _trCompletionSecs;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	SFDevice* _peerDevice;
	unsigned long long _peerFeatureFlags;
	UIViewController* _presentingViewController;
	/*^block*/id _progressHandler;
	/*^block*/id _promptForHomeHandler;
	/*^block*/id _promptForPINHandler;
	/*^block*/id _promptForRoomHandler;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;               //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (nonatomic,retain) SFDevice * peerDevice;                                    //@synthesize peerDevice=_peerDevice - In the implementation block
@property (assign,nonatomic) unsigned long long peerFeatureFlags;                      //@synthesize peerFeatureFlags=_peerFeatureFlags - In the implementation block
@property (nonatomic,retain) UIViewController * presentingViewController;              //@synthesize presentingViewController=_presentingViewController - In the implementation block
@property (nonatomic,copy) id progressHandler;                                         //@synthesize progressHandler=_progressHandler - In the implementation block
@property (nonatomic,copy) id promptForHomeHandler;                                    //@synthesize promptForHomeHandler=_promptForHomeHandler - In the implementation block
@property (nonatomic,copy) id promptForPINHandler;                                     //@synthesize promptForPINHandler=_promptForPINHandler - In the implementation block
@property (nonatomic,copy) id promptForRoomHandler;                                    //@synthesize promptForRoomHandler=_promptForRoomHandler - In the implementation block
-(void)setPresentingViewController:(UIViewController *)arg1 ;
-(id)progressHandler;
-(id)promptForPINHandler;
-(void)setPromptForPINHandler:(id)arg1 ;
-(void)pairSetupTryPIN:(id)arg1 ;
-(int)_runSFSessionStart;
-(id)promptForHomeHandler;
-(void)setPromptForHomeHandler:(id)arg1 ;
-(id)promptForRoomHandler;
-(void)setPromptForRoomHandler:(id)arg1 ;
-(int)_runPreflightWiFi;
-(int)_runTRSessionStart;
-(int)_runTRAuthentication;
-(int)_runCDPSetup;
-(int)_runHomeKitSetup;
-(int)_runFinish:(BOOL)arg1 ;
-(int)_runPreflightiTunes;
-(int)_runPreAuth;
-(int)_runPairSetup;
-(int)_runHomeKitUserInput;
-(int)_runBasicConfig;
-(int)_runTRSetupConfiguration;
-(int)_runTRNetwork;
-(int)_runTRActivation;
-(int)_runTRCompletion;
-(void)_reportError:(id)arg1 label:(id)arg2 ;
-(void)_runPreAuthRequest;
-(void)_runPreAuthResponse:(id)arg1 error:(id)arg2 ;
-(void)_runBasicConfigRequest;
-(void)_runBasicConfigResponse:(id)arg1 error:(id)arg2 ;
-(BOOL)_verifyiCloudMatch:(unsigned long long)arg1 error:(id*)arg2 ;
-(void)homeKitSelectHome:(id)arg1 ;
-(void)homeKitSelectRoom:(id)arg1 ;
-(unsigned long long)peerFeatureFlags;
-(void)setPeerFeatureFlags:(unsigned long long)arg1 ;
-(SFDevice *)peerDevice;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)setPeerDevice:(SFDevice *)arg1 ;
-(id)init;
-(void)dealloc;
-(UIViewController *)presentingViewController;
-(void)invalidate;
-(void)_cleanup;
-(void)activate;
-(void)setProgressHandler:(id)arg1 ;
-(void)_run;
@end

