/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:04 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/HMAccessoryBrowserDelegate.h>
#import <libobjc.A.dylib/HMHomeManagerDelegate.h>
#import <libobjc.A.dylib/HMHomeManagerDelegatePrivate.h>

@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSObject, TROperationQueue, HMHomeManager, HMAccessoryBrowser, HMDeviceSetupOperation, HMAccessory, HMRoom, NSDictionary, HMHome, NSString, ACAccount, TRSession;

@interface SFDeviceOperationHomeKitSetup : NSObject <HMAccessoryBrowserDelegate, HMHomeManagerDelegate, HMHomeManagerDelegatePrivate> {

	BOOL _active;
	BOOL _paused;
	unsigned long long _startTicks;
	int _state;
	NSObject*<OS_dispatch_source> _timeoutTimer;
	TROperationQueue* _trOperationQueue;
	HMHomeManager* _homeKitHomeManager;
	BOOL _homeKitHomeManagerReady;
	HMAccessoryBrowser* _homeKitBrowser;
	BOOL _homeAppInstallUserDidChoose;
	HMDeviceSetupOperation* _homeKitDeviceSetupOperation;
	HMAccessory* _homeKitAccessory;
	BOOL _reselectHome;
	HMRoom* _homeKitSelectedRoom;
	BOOL _homeKitAddedAccessory;
	BOOL _homeKitAddedAppData;
	BOOL _configuredStereoPair;
	BOOL _personalRequestsDone;
	BOOL _hasHomePod;
	BOOL _keyExchangeOnly;
	BOOL _pauseAfterUserInput;
	BOOL _personalRequestsEnabled;
	int _stereoRole;
	NSDictionary* _appDataSelf;
	/*^block*/id _completionHandler;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	HMHome* _homeKitSelectedHome;
	NSString* _homeKitSelectedRoomName;
	NSString* _iTunesAccountID;
	ACAccount* _iTunesAccount;
	double _metricNonUserSeconds;
	double _metricUserSeconds;
	/*^block*/id _pauseHandler;
	/*^block*/id _promptForHomeHandler;
	/*^block*/id _promptForRoomHandler;
	/*^block*/id _promptToInstallHomeAppHandler;
	HMAccessory* _stereoCounterpart;
	TRSession* _trSession;

}

@property (nonatomic,copy) NSDictionary * appDataSelf;                                //@synthesize appDataSelf=_appDataSelf - In the implementation block
@property (nonatomic,copy) id completionHandler;                                      //@synthesize completionHandler=_completionHandler - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (nonatomic,readonly) BOOL hasHomePod;                                       //@synthesize hasHomePod=_hasHomePod - In the implementation block
@property (nonatomic,readonly) HMHome * homeKitSelectedHome;                          //@synthesize homeKitSelectedHome=_homeKitSelectedHome - In the implementation block
@property (nonatomic,copy,readonly) NSString * homeKitSelectedRoomName;               //@synthesize homeKitSelectedRoomName=_homeKitSelectedRoomName - In the implementation block
@property (nonatomic,copy) NSString * iTunesAccountID;                                //@synthesize iTunesAccountID=_iTunesAccountID - In the implementation block
@property (nonatomic,retain) ACAccount * iTunesAccount;                               //@synthesize iTunesAccount=_iTunesAccount - In the implementation block
@property (assign,nonatomic) BOOL keyExchangeOnly;                                    //@synthesize keyExchangeOnly=_keyExchangeOnly - In the implementation block
@property (nonatomic,readonly) double metricNonUserSeconds;                           //@synthesize metricNonUserSeconds=_metricNonUserSeconds - In the implementation block
@property (nonatomic,readonly) double metricUserSeconds;                              //@synthesize metricUserSeconds=_metricUserSeconds - In the implementation block
@property (assign,nonatomic) BOOL pauseAfterUserInput;                                //@synthesize pauseAfterUserInput=_pauseAfterUserInput - In the implementation block
@property (nonatomic,copy) id pauseHandler;                                           //@synthesize pauseHandler=_pauseHandler - In the implementation block
@property (assign,nonatomic) BOOL personalRequestsEnabled;                            //@synthesize personalRequestsEnabled=_personalRequestsEnabled - In the implementation block
@property (nonatomic,copy) id promptForHomeHandler;                                   //@synthesize promptForHomeHandler=_promptForHomeHandler - In the implementation block
@property (nonatomic,copy) id promptForRoomHandler;                                   //@synthesize promptForRoomHandler=_promptForRoomHandler - In the implementation block
@property (nonatomic,copy) id promptToInstallHomeAppHandler;                          //@synthesize promptToInstallHomeAppHandler=_promptToInstallHomeAppHandler - In the implementation block
@property (nonatomic,retain) HMAccessory * stereoCounterpart;                         //@synthesize stereoCounterpart=_stereoCounterpart - In the implementation block
@property (assign,nonatomic) int stereoRole;                                          //@synthesize stereoRole=_stereoRole - In the implementation block
@property (nonatomic,retain) TRSession * trSession;                                   //@synthesize trSession=_trSession - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_completeWithError:(id)arg1 ;
-(void)_restoreHomeApp;
-(void)_startTimeout:(double)arg1 ;
-(BOOL)_isOwnerOfHome:(id)arg1 ;
-(void)_runInit;
-(id)_runHomeKitAutoSelectHome:(BOOL)arg1 ;
-(void)_updateHomeHasHomePod;
-(void)_runHomeKitSelectRoom;
-(void)_runHomeKitDeviceSetup;
-(void)_runHomeKitAddAccessory;
-(void)_runHomeKitSetupRoom;
-(void)_runHomeKitAssignRoom;
-(void)_runHomeKitAddAppData;
-(BOOL)_runHomeKitConfigureStereoPairAndReturnError:(id*)arg1 ;
-(void)_runPersonalRequestsStart;
-(void)_runHomeKitAddHome;
-(void)_removeSimilarRoomNames:(id)arg1 home:(id)arg2 ;
-(id)_normalizedString:(id)arg1 ;
-(void)_updateAccount;
-(id)_mediaSystemForAccessory:(id)arg1 ;
-(void)homeAppInstallChoice:(BOOL)arg1 ;
-(void)selectHome:(id)arg1 ;
-(void)reselectHome;
-(void)selectRoom:(id)arg1 ;
-(id)findStereoCounterparts;
-(NSDictionary *)appDataSelf;
-(void)setAppDataSelf:(NSDictionary *)arg1 ;
-(BOOL)hasHomePod;
-(HMHome *)homeKitSelectedHome;
-(NSString *)homeKitSelectedRoomName;
-(NSString *)iTunesAccountID;
-(void)setITunesAccountID:(NSString *)arg1 ;
-(ACAccount *)iTunesAccount;
-(void)setITunesAccount:(ACAccount *)arg1 ;
-(BOOL)keyExchangeOnly;
-(void)setKeyExchangeOnly:(BOOL)arg1 ;
-(double)metricNonUserSeconds;
-(double)metricUserSeconds;
-(BOOL)pauseAfterUserInput;
-(void)setPauseAfterUserInput:(BOOL)arg1 ;
-(id)pauseHandler;
-(void)setPauseHandler:(id)arg1 ;
-(BOOL)personalRequestsEnabled;
-(void)setPersonalRequestsEnabled:(BOOL)arg1 ;
-(id)promptForHomeHandler;
-(void)setPromptForHomeHandler:(id)arg1 ;
-(id)promptForRoomHandler;
-(void)setPromptForRoomHandler:(id)arg1 ;
-(id)promptToInstallHomeAppHandler;
-(void)setPromptToInstallHomeAppHandler:(id)arg1 ;
-(HMAccessory *)stereoCounterpart;
-(void)setStereoCounterpart:(HMAccessory *)arg1 ;
-(int)stereoRole;
-(void)setStereoRole:(int)arg1 ;
-(TRSession *)trSession;
-(void)setTrSession:(TRSession *)arg1 ;
-(void)homeManagerDidUpdateHomes:(id)arg1 ;
-(void)homeManagerDidUpdateDataSyncState:(id)arg1 ;
-(void)homeManager:(id)arg1 didUpdateStatus:(unsigned long long)arg2 ;
-(void)accessoryBrowser:(id)arg1 didFindNewAccessory:(id)arg2 ;
-(void)accessoryBrowser:(id)arg1 didRemoveNewAccessory:(id)arg2 ;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(id)init;
-(void)invalidate;
-(id)completionHandler;
-(void)_cleanup;
-(void)activate;
-(void)resume;
-(void)setCompletionHandler:(id)arg1 ;
-(void)_run;
@end

