/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:04 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Sharing/Sharing-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSUUID, SFDevice, NSData, NSDictionary, SFSession, NSSet;

@interface SFMessage : NSObject <NSSecureCoding> {

	NSUUID* _identifier;
	SFDevice* _peerDevice;
	BOOL _expectsResponse;
	NSData* _bodyData;
	/*^block*/id _completionHandler;
	NSDictionary* _headerFields;
	SFSession* _session;
	NSSet* _deviceIDs;

}

@property (nonatomic,copy) NSSet * deviceIDs;                        //@synthesize deviceIDs=_deviceIDs - In the implementation block
@property (nonatomic,copy) NSUUID * identifier;                      //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) SFSession * session;                    //@synthesize session=_session - In the implementation block
@property (nonatomic,copy) NSData * bodyData;                        //@synthesize bodyData=_bodyData - In the implementation block
@property (nonatomic,copy) id completionHandler;                     //@synthesize completionHandler=_completionHandler - In the implementation block
@property (assign,nonatomic) BOOL expectsResponse;                   //@synthesize expectsResponse=_expectsResponse - In the implementation block
@property (nonatomic,copy) NSDictionary * headerFields;              //@synthesize headerFields=_headerFields - In the implementation block
@property (nonatomic,retain) SFDevice * peerDevice;                  //@synthesize peerDevice=_peerDevice - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSDictionary *)headerFields;
-(void)setSession:(SFSession *)arg1 ;
-(SFSession *)session;
-(NSData *)bodyData;
-(void)setHeaderFields:(NSDictionary *)arg1 ;
-(void)setBodyData:(NSData *)arg1 ;
-(BOOL)expectsResponse;
-(void)setExpectsResponse:(BOOL)arg1 ;
-(NSSet *)deviceIDs;
-(void)setDeviceIDs:(NSSet *)arg1 ;
-(SFDevice *)peerDevice;
-(void)setPeerDevice:(SFDevice *)arg1 ;
-(NSUUID *)identifier;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
-(void)setIdentifier:(NSUUID *)arg1 ;
-(void)invalidate;
-(id)completionHandler;
-(void)setCompletionHandler:(id)arg1 ;
@end

