/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:04 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSNumber, NSString;

@interface SFPasswordSharingInfo : NSObject <NSSecureCoding> {

	NSNumber* _channel;
	NSString* _networkName;
	NSString* _psk;

}

@property (nonatomic,retain) NSNumber * channel;                  //@synthesize channel=_channel - In the implementation block
@property (nonatomic,retain) NSString * networkName;              //@synthesize networkName=_networkName - In the implementation block
@property (nonatomic,retain) NSString * psk;                      //@synthesize psk=_psk - In the implementation block
+(BOOL)supportsSecureCoding;
-(void)setChannel:(NSNumber *)arg1 ;
-(NSNumber *)channel;
-(NSString *)networkName;
-(void)setNetworkName:(NSString *)arg1 ;
-(void)setPsk:(NSString *)arg1 ;
-(NSString *)psk;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
@end

