/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:47:02 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFXPCInterface
@optional
-(void)autoFillDismissUserNotification;
-(void)autoFillPairingSucceeded:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)autoFillPromptForPIN:(unsigned)arg1 throttleSeconds:(int)arg2;
-(void)deviceDiscoveryFoundDevice:(id)arg1;
-(void)deviceDiscoveryLostDevice:(id)arg1;
-(void)deviceDiscoveryDeviceChanged:(id)arg1 changes:(unsigned)arg2;
-(void)deviceDiscoveryScanStateChanged:(long long)arg1;
-(void)remoteInteractionSessionRemoteTextEvent:(id)arg1;
-(void)remoteInteractionSessionTextSessionDidBegin:(id)arg1;
-(void)remoteInteractionSessionTextSessionDidEnd:(id)arg1;
-(void)remoteInteractionSessionTextSessionDidChange:(id)arg1;
-(void)serviceError:(id)arg1;
-(void)servicePeerDisconnected:(id)arg1 error:(id)arg2;
-(void)serviceReceivedEvent:(id)arg1;
-(void)serviceReceivedFrameType:(unsigned char)arg1 data:(id)arg2 peer:(id)arg3;
-(void)serviceReceivedRequest:(id)arg1;
-(void)serviceReceivedResponse:(id)arg1;
-(void)sessionBluetoothStateChanged:(long long)arg1;
-(void)sessionError:(id)arg1;
-(void)sessionReceivedEvent:(id)arg1;
-(void)sessionReceivedFrameType:(unsigned char)arg1 data:(id)arg2;
-(void)sessionReceivedRequest:(id)arg1;
-(void)sessionReceivedResponse:(id)arg1;
-(void)userNotificationError:(id)arg1;
-(void)userNotificationResponse:(int)arg1;
-(void)userNotificationTextResponse:(id)arg1;

@end

