/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:31 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSURL, LSApplicationProxy, _LSValidationToken;

@interface LSAppLink : NSObject <NSSecureCoding> {

	NSURL* _URL;
	LSApplicationProxy* _targetApplicationProxy;
	_LSValidationToken* __validationToken;

}

@property (assign) long long openStrategy; 
@property (retain) _LSValidationToken * _validationToken;                    //@synthesize _validationToken=__validationToken - In the implementation block
@property (copy) NSURL * URL;                                                //@synthesize URL=_URL - In the implementation block
@property (retain) LSApplicationProxy * targetApplicationProxy;              //@synthesize targetApplicationProxy=_targetApplicationProxy - In the implementation block
+(id)dispatchQueue;
+(BOOL)URLComponentsAreValidForAppLinks:(id)arg1 error:(id*)arg2 ;
+(void)getAppLinksWithURL:(id)arg1 limit:(unsigned long long)arg2 completionHandler:(/*^block*/id)arg3 ;
+(void)openWithURL:(id)arg1 configuration:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
+(void)getAppLinksWithURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
+(void)_openWithAppLink:(id)arg1 state:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
+(void)_getAppLinksFromPlugInAtIndex:(unsigned long long)arg1 forURLComponents:(id)arg2 limit:(unsigned long long)arg3 XPCConnection:(id)arg4 results:(id)arg5 completionHandler:(/*^block*/id)arg6 ;
+(long long)_openStrategyForBundleIdentifier:(id)arg1 ;
+(BOOL)_shouldAppLinkOpenWithStrategy:(long long)arg1 state:(id)arg2 XPCConnection:(id)arg3 ;
+(void)_getAppLinksWithURL:(id)arg1 limit:(unsigned long long)arg2 requireEntitlement:(BOOL)arg3 XPCConnection:(id)arg4 completionHandler:(/*^block*/id)arg5 ;
+(id)_appLinkWithURL:(id)arg1 applicationProxy:(id)arg2 plugIn:(id)arg3 ;
+(void)_openWithAppLink:(id)arg1 state:(id)arg2 XPCConnection:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
+(BOOL)_XPCConnectionIsBrowser:(id)arg1 ;
+(void)_setOpenStrategy:(long long)arg1 forBundleIdentifier:(id)arg2 XPCConnection:(id)arg3 ;
+(BOOL)supportsSecureCoding;
+(void)openWithURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
+(void)getAppLinkWithURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(_LSValidationToken *)_validationToken;
-(void)openWithConfiguration:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(LSApplicationProxy *)targetApplicationProxy;
-(void)setTargetApplicationProxy:(LSApplicationProxy *)arg1 ;
-(void)set_validationToken:(_LSValidationToken *)arg1 ;
-(id)_validationTokenPayload;
-(long long)openStrategy;
-(void)openInWebBrowser:(BOOL)arg1 setOpenStrategy:(long long)arg2 webBrowserState:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)openInWebBrowser:(BOOL)arg1 setOpenStrategy:(long long)arg2 webBrowserState:(id)arg3 configuration:(id)arg4 completionHandler:(/*^block*/id)arg5 ;
-(void)setOpenStrategy:(long long)arg1 ;
-(void)openInWebBrowser:(BOOL)arg1 setAppropriateOpenStrategyAndWebBrowserState:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(unsigned long long)hash;
-(id)debugDescription;
-(NSURL *)URL;
-(void)setURL:(NSURL *)arg1 ;
-(void)openWithCompletionHandler:(/*^block*/id)arg1 ;
@end

