//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep  9 2019 14:18:44).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumber.h>

@interface NSNumber (TVASMilliseconds)
+ (id)tvas_numberInMillisecondsWithTimeInterval:(double)arg1;	// IMP=0x0000000100010f54
@end

